export interface PersonaContent {
  id: string;
  label: string;
  today: string;
  hundredX: string;
  impact: string;
  example: string;
}

export const PERSONAS = [
  { id: "founder", label: "Founder / CEO" },
  { id: "pm", label: "Product Manager" },
  { id: "designer", label: "Product Designer" },
  { id: "engineer", label: "Engineering Lead" },
  { id: "ops", label: "Operations Leader" },
  { id: "clinical", label: "Clinical Leader" },
];

export const PERSONA_CONTENT: Record<string, PersonaContent[]> = {
  "pillar-1-knowledge-management": [
    {
      id: "founder",
      label: "Founder / CEO",
      today: "You repeat the same strategic context in every meeting. New hires take months to absorb institutional knowledge. Your AI tools know nothing about your market, customers, or competitive position.",
      hundredX: "Your knowledge base captures every customer call, board insight, and strategic decision. **AI drafts investor updates, competitive analyses, and strategic memos grounded in your actual context** — not generic templates.",
      impact: "Your company's accumulated intelligence becomes a moat competitors can't buy. Every month widens the gap.",
      example: "A founder encoded 200+ pitch meeting learnings into a knowledge base. Investor updates went from 3 hours to 20 minutes — more personalized than before because the AI references each investor's specific interests.",
    },
    {
      id: "pm",
      label: "Product Manager",
      today: "You write every brief from scratch. Your AI doesn't know your personas, KPIs, or competitive landscape. You spend more time assembling context than making decisions.",
      hundredX: "Your knowledge base holds persona research, feature performance data, and competitive positioning. **AI drafts briefs with specificity that used to take days of research** — because the context is already structured.",
      impact: "You shift from context assembly to strategic judgment. Brief quality goes up while time drops 80%.",
      example: "A PM encoded user research, competitive intel, and KPI targets. Sprint planning briefs now auto-draft with references to specific persona pain points and success metrics. Research time dropped from 2 days to 30 minutes.",
    },
    {
      id: "designer",
      label: "Product Designer",
      today: "AI-generated designs look like everyone else's. Your taste — the typography instincts, spacing sensibility, and quality bar that define your work — is invisible to every tool you use.",
      hundredX: "Your design knowledge base captures your taste framework, component principles, and aesthetic rules. **AI produces work that matches your aesthetic on the first try** — no more \"make it less corporate\" loops.",
      impact: "Your taste becomes a scalable asset. Junior designers produce work matching your quality bar because the knowledge base carries your judgment.",
      example: "A designer documented 40 principles about typography, spacing, and interaction patterns. Monday's AI-generated homepage concepts matched her aesthetic perfectly — saving 2 days of iteration per project.",
    },
    {
      id: "engineer",
      label: "Engineering Lead",
      today: "AI code suggestions ignore your naming conventions, use deprecated patterns, and don't know about shared utilities. Your team spends 15 minutes per suggestion fixing it to match your standards.",
      hundredX: "Your engineering knowledge base encodes architecture patterns, conventions, and technical debt. **Code suggestions respect your actual stack** — not generic patterns from training data.",
      impact: "Code review shifts from catching style violations to discussing architecture. Onboarding time for new engineers drops from months to weeks.",
      example: "An engineering lead documented his team's patterns, naming conventions, and the 5 things you should never do in this codebase. AI code suggestions went from 60% acceptance to 95% — with zero post-edit fixes.",
    },
    {
      id: "ops",
      label: "Operations Leader",
      today: "Your team's operational knowledge lives in people's heads. When someone leaves, context walks out the door. AI tools give you generic process advice that doesn't fit your reality.",
      hundredX: "Your ops knowledge base captures workflows, escalation paths, and institutional decisions. **AI routes work with full context and surfaces relevant precedents** for every decision.",
      impact: "Operational knowledge compounds instead of leaking. New team members reach full productivity 3x faster because the knowledge base carries institutional memory.",
      example: "An ops leader encoded care coordination protocols, vendor relationships, and escalation logic. New hires' AI assistants answered operational questions with specificity that used to require 3 months of shadowing.",
    },
    {
      id: "clinical",
      label: "Clinical Leader",
      today: "Clinical knowledge is scattered across EHRs, protocols, and individual clinicians' experience. AI gives you textbook answers that ignore your patient population's specific needs.",
      hundredX: "Your clinical knowledge base holds care protocols, patient population insights, and outcome data. **AI pre-assembles patient context with your specific clinical frameworks** — not generic guidelines.",
      impact: "Clinicians spend time on clinical judgment instead of information assembly. Care quality improves because no context gets missed.",
      example: "A clinical team encoded assessment frameworks and care protocols. Pre-visit prep dropped from 45 minutes to 5 — with more complete context because the AI cross-references the full patient history automatically.",
    },
  ],

  "taste-through-ai": [
    {
      id: "founder",
      label: "Founder / CEO",
      today: "Your brand voice, communication style, and quality bar exist only in your head. Every piece of content requires your review because no one else can match your standards.",
      hundredX: "Your taste doc captures your communication principles — candor level, how you frame challenges, which metrics lead. **AI produces communications that sound like you** without your bottleneck.",
      impact: "You stop being the quality bottleneck. Your taste scales across the organization without requiring your review on everything.",
      example: "A founder encoded his investor communication style: level of candor, how challenges become opportunities, metrics that always lead. Investor updates now take 20 minutes and are more personalized than his 3-hour manual versions.",
    },
    {
      id: "pm",
      label: "Product Manager",
      today: "Your briefs sound like generic templates. The specific way you frame problems, structure success metrics, and balance stakeholder needs — your PM craft — gets lost in AI output.",
      hundredX: "Your taste doc captures how you structure problem statements, what evidence you consider sufficient, and how you frame success metrics. **AI drafts briefs that sound like your best work**, not a template.",
      impact: "Your brief-writing craft becomes a documented asset. You produce twice as many briefs at higher quality because the AI starts from your judgment, not from zero.",
      example: "A PM documented her brief-writing principles: how she structures problem statements, required customer evidence thresholds, and success metric framing. First drafts now match her quality bar — saving a full day per brief.",
    },
    {
      id: "designer",
      label: "Product Designer",
      today: "You spend hours editing AI output to match your aesthetic. The 2px spacing instinct, the typography weight preferences, the color temperature sensitivity — none of it reaches your tools.",
      hundredX: "Your taste doc has 10–15 specific rules per design domain. **AI output matches your aesthetic on the first generation** because it knows your spacing system, type hierarchy, and color principles.",
      impact: "Your design taste becomes a compounding asset. Every project starts from your quality bar instead of from generic defaults.",
      example: "A designer wrote 40 specific principles: body text never exceeds 18px, line height always 1.5x, primary CTAs use high-contrast fills never outlines. AI-generated designs matched her aesthetic without a single correction.",
    },
    {
      id: "engineer",
      label: "Engineering Lead",
      today: "AI-generated code technically works but doesn't feel like your codebase. Variable names are wrong, patterns are outdated, and the abstraction choices don't match your team's philosophy.",
      hundredX: "Your engineering taste doc captures naming conventions, abstraction philosophy, and quality thresholds. **Generated code feels native to your codebase** because it respects your engineering craft.",
      impact: "Code review time drops dramatically. Junior engineers produce code that matches senior patterns because the taste doc carries the team's craft.",
      example: "An engineer documented his team's state management approach, API conventions, and component structure standards. AI suggestions now follow team patterns — the 'fix it to match our style' step disappeared entirely.",
    },
    {
      id: "ops",
      label: "Operations Leader",
      today: "Process documentation is either too generic to be useful or too specific to maintain. Your operational judgment about what matters gets lost in template-driven work.",
      hundredX: "Your ops taste doc captures how you evaluate workflows, what 'good enough' means for different processes, and your escalation philosophy. **AI recommendations match your operational judgment**, not textbook ideals.",
      impact: "Process improvements happen faster because AI suggestions already reflect your standards. Teams make better autonomous decisions because your judgment is encoded.",
      example: "An ops leader documented her escalation philosophy and process quality thresholds. AI-generated workflow recommendations now match her judgment about when to automate vs. keep manual — saving weeks of back-and-forth.",
    },
    {
      id: "clinical",
      label: "Clinical Leader",
      today: "Clinical documentation follows templates that don't reflect your care philosophy. Your approach to patient communication, risk assessment, and care planning is invisible to AI tools.",
      hundredX: "Your clinical taste doc captures your care philosophy, communication standards, and documentation quality bar. **AI-generated clinical content reflects your specific approach** to patient care.",
      impact: "Clinical documentation quality becomes consistent across your team. New clinicians adopt your care standards faster because they're encoded, not just taught.",
      example: "A clinical leader encoded her documentation standards, patient communication tone, and risk assessment framework. AI-assisted notes now reflect her care philosophy — compliance flagging dropped 80% because quality was built in.",
    },
  ],

  "speed-to-market": [
    {
      id: "founder",
      label: "Founder / CEO",
      today: "Your product roadmap is full of features that have been 'in progress' for months. The gap between idea and shipping keeps growing as your team spends more time planning than building.",
      hundredX: "Every stage of your pipeline — brief, design, build, deploy — shares context automatically. **Ideas reach production in days instead of quarters** because no one waits for information that already exists.",
      impact: "You learn 4x faster than competitors shipping monthly. After a quarter, you've run 12 experiments to their 3. Speed becomes your moat.",
      example: "A founder went from idea to live patient portal in 2.5 weeks — work that traditionally takes 6 months. AI-assembled context at every stage eliminated the dead time between decisions.",
    },
    {
      id: "pm",
      label: "Product Manager",
      today: "You spend 70% of your day assembling context — pulling data from dashboards, reading Slack threads, gathering customer feedback — before you make a single decision.",
      hundredX: "Your AI assembles a pre-sprint brief overnight: data, trends, feedback mapped to roadmap items. **You walk in Monday with context that used to take until lunch** — and start deciding immediately.",
      impact: "You reclaim a half-day of building time every week. Sprint velocity increases not because the team works more, but because decisions happen 3x faster.",
      example: "A PM measured his Monday morning: 45 min on dashboards, 20 min on Slack, 30 min on feedback. After building context packages, his AI assembles it overnight. Sprint planning starts at 9am instead of 2pm.",
    },
    {
      id: "designer",
      label: "Product Designer",
      today: "You spend 2 hours researching patterns and pulling references before starting any design. By the time you start creating, half the day is gone.",
      hundredX: "Context packages include your design system, competitor patterns, and accessibility requirements. **You prompt with constraints and start from a meaningful first draft** instead of a blank canvas.",
      impact: "Time to first reviewable mockup drops from 2 days to 3 hours. You explore 5 directions in the time it used to take to develop 1.",
      example: "A designer built context packages with her design system, tagged competitor screenshots, and accessibility rules. She now generates 5 directions in a morning and presents the strongest 2 with evidence — quality went up 60%.",
    },
    {
      id: "engineer",
      label: "Engineering Lead",
      today: "Your team waits for specs, then waits for design review, then waits for QA. Each handoff loses context. By shipping time, nobody has the full picture.",
      hundredX: "AI maintains full context across every handoff. Specs include design rationale, designs include engineering constraints, PRs include business context. **No one spends a day re-establishing what the last person already figured out.**",
      impact: "Idea-to-production cycle compresses from 6 weeks to 8 days. Your team learns faster because they ship faster.",
      example: "A team cut their cycle from 6 weeks to 8 days by eliminating context loss at handoffs. Each step's AI had access to every previous step's output plus the shared knowledge base.",
    },
    {
      id: "ops",
      label: "Operations Leader",
      today: "New process deployments take 8 weeks of requirements gathering, vendor coordination, and manual configuration. By launch, the original need has already shifted.",
      hundredX: "Your orchestration hub handles routing and integration. Your knowledge base provides protocols. **AI assembles the configuration, humans review and approve.** Deployment time drops from weeks to days.",
      impact: "You respond to operational needs in real-time instead of planning quarters ahead. Your team becomes the fastest-moving function in the company.",
      example: "A clinical ops team deployed a new care workflow in 48 hours instead of the typical 8-week IT project. The hub handled routing, the knowledge base provided protocols, AI assembled the config.",
    },
    {
      id: "clinical",
      label: "Clinical Leader",
      today: "Implementing new care protocols takes months of training, documentation, and compliance review. Clinicians resist changes because adoption is disruptive and slow.",
      hundredX: "New protocols encode directly into the knowledge base. AI-assisted workflows **adopt the protocol automatically** — clinicians see updated guidance in their pre-visit prep without separate training.",
      impact: "Protocol adoption goes from months to days. Clinicians embrace changes because the system handles the transition — no extra cognitive load.",
      example: "A clinical team updated their assessment protocol. Instead of 6 weeks of training sessions, they encoded it in the knowledge base. Clinicians' AI-assembled prep reflected the new protocol the next morning.",
    },
  ],

  "pillar-3-orchestration": [
    {
      id: "founder",
      label: "Founder / CEO",
      today: "You're managing 12 Slack channels, 5 dashboards, and a whiteboard of priorities. Information flows through you because no system connects the dots automatically.",
      hundredX: "An orchestration layer routes information, triggers workflows, and surfaces decisions to the right person with context attached. **You focus on strategy because the machine handles coordination.**",
      impact: "You stop being the information bottleneck. The company moves at system speed, not calendar speed.",
      example: "A founder running 12 simultaneous projects uses AI agents with orchestration logic. Each project's context flows automatically — no manual status updates, no coordination meetings, no information lost between channels.",
    },
    {
      id: "pm",
      label: "Product Manager",
      today: "You spend more time coordinating between teams than making product decisions. Status meetings exist because there's no shared system connecting work across functions.",
      hundredX: "Workflow orchestration connects research, design, engineering, and launch. **Each function sees the full context automatically** — decisions flow without coordination meetings.",
      impact: "Standup drops from 30 minutes to 12. You spend your time on product judgment, not information routing.",
      example: "A PM's orchestration layer pulls overnight feedback, maps it to the roadmap, and assembles a sprint brief. He walks into standup with full context. The first 18 minutes of 'catching up' disappeared.",
    },
    {
      id: "designer",
      label: "Product Designer",
      today: "You walk into design reviews spending the first 20 minutes re-establishing context. Persona data, previous decisions, and constraints aren't available where you need them.",
      hundredX: "Before each review, AI pulls persona data, references design system patterns, and flags accessibility issues. **You walk in ready for strategic discussion**, not context assembly.",
      impact: "Design reviews become about creative direction instead of information sharing. Quality goes up because more time goes to judgment.",
      example: "A designer's pre-review AI assembles persona data, similar patterns from the design system, and accessibility flags. The first 20 minutes of 'let me catch everyone up' became 20 minutes of strategic design discussion.",
    },
    {
      id: "engineer",
      label: "Engineering Lead",
      today: "Your team spends 30% of sprint time on context gathering — reading tickets, tracing requirements back to product decisions, understanding why something was built a certain way.",
      hundredX: "Orchestration attaches full context to every ticket: product rationale, design decisions, technical constraints, and related past work. **Engineers start building on day 1 of the sprint**, not day 3.",
      impact: "Sprint velocity increases 30% without more hours. Engineers make better architectural decisions because they have the full picture.",
      example: "An engineering team's orchestration layer attaches business context, design rationale, and related PRs to every ticket. 'Why was it built this way?' questions dropped 80% — the answer is in the ticket.",
    },
    {
      id: "ops",
      label: "Operations Leader",
      today: "Task A is automated. Task B is automated. The workflow between them — routing, conditional logic, exception handling — is still entirely manual.",
      hundredX: "An event-driven orchestration engine runs complex conditional chains with escalation paths and human checkpoints. **The full workflow is automated**, not just individual tasks.",
      impact: "Throughput increases 3x without adding headcount. Your team focuses on complex decisions, not routine routing.",
      example: "A clinical ops team built an event-driven engine: patient data triggers a cascade — check history, compare baselines, assess protocols, route to the right team member with full context. Prep time dropped from 45 to 5 minutes.",
    },
    {
      id: "clinical",
      label: "Clinical Leader",
      today: "Clinicians spend 40% of their time on information assembly — pulling data from multiple systems, reading through history, manually piecing together the patient picture.",
      hundredX: "AI pre-assembles complete patient context before every encounter. **Clinicians walk in with everything they need** — history, trends, flags, and decision-relevant data assembled automatically.",
      impact: "Clinical decision quality improves because no context gets missed. Patient throughput increases 3x because assembly time drops to near zero.",
      example: "A care coordinator used to spend 45 minutes prepping per patient review. Orchestration now pre-assembles context: relevant history, flagged trends, protocol-relevant data. Prep dropped to 5 minutes. Decision quality went up.",
    },
  ],

  "10x-team-ai-peers": [
    {
      id: "founder",
      label: "Founder / CEO",
      today: "Your roadmap needs 50 people but you have 5. Hiring takes months. Contractors need onboarding. You're choosing between moving slow and moving sloppy.",
      hundredX: "Each team member operates with 2–5 AI peers handling context-heavy work in their domain. **A team of 5 produces the output of 15** because humans focus on judgment while AI handles assembly.",
      impact: "Your headcount math changes permanently. You hire for judgment and taste, not throughput. Burn rate drops while output increases.",
      example: "A founder runs 12 simultaneous projects with AI agents. Each workstream has its own context: competitive research, outreach drafts, architecture docs, product specs. She reviews and refines — the assembly work is handled.",
    },
    {
      id: "pm",
      label: "Product Manager",
      today: "You're one PM covering 3 product areas. Each area needs research, briefs, stakeholder alignment, and launch planning. Something always gets neglected.",
      hundredX: "AI peers handle research synthesis, brief drafting, and competitive monitoring for each area. **You direct and refine instead of assembling from scratch.** Coverage goes from partial to complete.",
      impact: "You cover 3 product areas at the quality of covering 1. Nothing gets neglected because the assembly layer never sleeps.",
      example: "A PM set up AI peers for each product area: one monitors competitive moves, one synthesizes user feedback, one drafts briefs from the knowledge base. She reviews and refines — all 3 areas get equal strategic attention.",
    },
    {
      id: "designer",
      label: "Product Designer",
      today: "You're the only designer. You handle UX, visual design, research synthesis, and design system maintenance. Your best work suffers because you're spread too thin.",
      hundredX: "AI peers generate design variations, test responsive layouts, produce asset sets, and maintain your design system. **You focus on creative direction and quality review** — the highest-value use of your taste.",
      impact: "A design team of 2 produces the output of 8. Your taste and judgment scale without burning out.",
      example: "A design team of 2 uses AI peers running through their design system, component library, and brand docs. Designers focus on creative direction. AI handles variations, responsive layouts, and asset generation — 4x output.",
    },
    {
      id: "engineer",
      label: "Engineering Lead",
      today: "Your team is underwater on features and the test suite is thin. Documentation is a quarter behind. Code review takes days because everyone is at capacity.",
      hundredX: "AI peers handle code review prep, test generation, documentation, and refactoring plans — grounded in your architecture docs. **Your engineers focus on architecture and complex logic**, not boilerplate.",
      impact: "Review cycles drop from days to hours. Test coverage doubles. Documentation stays current. Your team builds more because they maintain less.",
      example: "An engineering lead uses AI peers for code review prep, test generation, and documentation — all grounded in the team's architecture docs and coding standards. Review cycles dropped from 2 days to 4 hours.",
    },
    {
      id: "ops",
      label: "Operations Leader",
      today: "Your team of 5 manages workflows that traditionally need 15 people. Everyone is stretched. Quality drops when volume spikes because there's no buffer.",
      hundredX: "AI peers handle intake assembly, routine communication drafts, data synthesis, and scheduling. **Humans handle complex cases and relationship decisions.** Volume spikes don't break the team.",
      impact: "You scale operations without scaling headcount. Quality stays consistent because the routine work never slips regardless of volume.",
      example: "A clinical ops team of 3 manages a patient load that traditionally needs 10 coordinators. AI peers handle intake, scheduling, and routine communications. Humans handle complex clinical decisions and relationship-sensitive interactions.",
    },
    {
      id: "clinical",
      label: "Clinical Leader",
      today: "Your clinicians spend more time on documentation and coordination than on patient care. Adding patient volume means adding headcount — there's no other way to scale.",
      hundredX: "AI peers handle documentation, intake assembly, and care coordination logistics. **Clinicians focus on clinical judgment and patient relationships** — the work only humans should do.",
      impact: "Patient throughput increases without clinician burnout. Care quality improves because clinicians spend their time where their expertise matters most.",
      example: "A clinical team uses AI peers for intake assembly, scheduling coordination, and documentation. Clinicians focus purely on clinical decisions and patient relationships. Patient volume increased 40% with no added clinical headcount.",
    },
  ],

  "coding-in-craft": [
    {
      id: "founder",
      label: "Founder / CEO",
      today: "Your development team ships code that works but doesn't reflect your company's quality standards. Technical debt accumulates because AI suggestions don't know your constraints.",
      hundredX: "Your engineering context package encodes architecture decisions, quality standards, and technical debt strategy. **Every AI-generated line respects your actual constraints**, not generic best practices.",
      impact: "Technical debt stops accumulating silently. New engineers contribute production-quality code in week 1 because the context carries your standards.",
      example: "A startup CTO encoded stack constraints — deployment pipeline, database conventions, API versioning, and critical services. New engineers' AI suggestions respect all constraints from day one. Onboarding dropped from 3 months to 2 weeks.",
    },
    {
      id: "pm",
      label: "Product Manager",
      today: "You write requirements and throw them over the wall. Engineering interprets them differently than you intended because context gets lost in translation.",
      hundredX: "Your requirements connect to the engineering knowledge base. **Technical constraints, past decisions, and architecture context automatically inform spec interpretation.** Fewer surprises at review.",
      impact: "Engineering builds what you meant, not what they inferred. Back-and-forth clarification cycles drop 70%.",
      example: "A PM's specs now reference the engineering knowledge base. When she writes 'add offline mode,' the AI surfaces the 3 architecture constraints and 2 previous attempts — engineering gets the full picture in the spec.",
    },
    {
      id: "designer",
      label: "Product Designer",
      today: "You hand off designs and the implementation looks different. Your design tokens, spacing system, and interaction patterns get translated incorrectly in code.",
      hundredX: "Your design system connects to the engineering context. **AI-generated code uses your actual components with your actual tokens.** The gap between design and implementation closes.",
      impact: "Implementation matches design on the first build. The QA cycle that used to catch visual discrepancies shrinks to near zero.",
      example: "A design engineer connected his component library, design tokens, and accessibility requirements to his coding AI. Generated code uses his actual components with his actual tokens — no more translating from generic React.",
    },
    {
      id: "engineer",
      label: "Engineering Lead",
      today: "Copilot autocompletes functions that ignore your naming conventions, use deprecated patterns, and don't know about shared utilities. Your team edits every suggestion to match standards.",
      hundredX: "Your engineering context encodes patterns, conventions, utilities, and anti-patterns. **Code suggestions are native to your codebase** — acceptance rate jumps from 60% to 95%.",
      impact: "Code review shifts from catching style violations to discussing architecture. Senior engineer time reclaims 30% from review overhead.",
      example: "An engineer documented patterns, conventions, and '5 things never to do' in this codebase. AI suggestions now follow team patterns. Code review went from 'please follow our style' to 'let's discuss the architecture choice.'",
    },
    {
      id: "ops",
      label: "Operations Leader",
      today: "Internal tools are built by engineers who don't understand your workflows. The tools technically work but don't match how your team actually operates.",
      hundredX: "Your operational context encodes workflows, decision logic, and process requirements. **AI-generated internal tools reflect your actual operations**, not engineering assumptions about them.",
      impact: "Internal tools get adopted because they match real workflows. The gap between what engineering builds and what ops needs closes.",
      example: "An ops leader encoded her team's actual workflows, escalation logic, and decision criteria. AI-generated tooling suggestions now match operational reality — adoption went from 40% to 90% on internal tools.",
    },
    {
      id: "clinical",
      label: "Clinical Leader",
      today: "Clinical software is built by engineers who don't understand clinical workflows. Compliance requirements get bolted on after the fact, creating friction for clinicians.",
      hundredX: "HIPAA patterns, audit logging, and clinical workflow requirements encode into the engineering context. **Every code change automatically follows compliance patterns** from the start.",
      impact: "Security review flags drop from 40% of PRs to 5%. Clinical software fits clinical workflows because the constraints are in the AI, not just in the requirements doc.",
      example: "A clinical software team encoded HIPAA compliance patterns, audit logging requirements, and data handling conventions. AI-generated code changes follow compliance patterns automatically. Security review flags dropped from 40% to 5%.",
    },
  ],

  "collaborative-spaces": [
    {
      id: "founder",
      label: "Founder / CEO",
      today: "Your team uses AI in isolation. The PM prompts Claude, copies output to Notion, Slacks the designer. The designer opens a new session with zero context. Three people using AI. Zero collaboration.",
      hundredX: "Shared workspaces where human and AI contributions live side by side. **When any team member asks a question, the AI answers with the full organizational context** — not just their slice.",
      impact: "Information flows without meetings. Decisions happen faster because everyone — human and AI — works from the same complete picture.",
      example: "A company built shared interfaces for business, clinical, and ops teams — all reading from the same central platform. When business updates a customer insight, the clinical team's AI immediately has that context.",
    },
    {
      id: "pm",
      label: "Product Manager",
      today: "Your product research lives in your head and your Notion pages. The designer doesn't see it when designing. Engineering doesn't see it when building. You're the information bottleneck.",
      hundredX: "A shared research surface feeds all functions. **When the designer asks about user needs, the AI answers with your research.** When engineering asks about priorities, the AI references your evidence.",
      impact: "You stop being the human API between functions. Product context flows to whoever needs it, whenever they need it, without a meeting.",
      example: "A product team built a shared research surface: interviews, competitive analysis, and usage data all feed one AI-accessible layer. Any team member's question gets answered with the full research context — no Slack DMs needed.",
    },
    {
      id: "designer",
      label: "Product Designer",
      today: "You design in Figma, the PM writes in Notion, engineering builds in VS Code. Each tool is a silo. Your design decisions have no visibility to the rest of the team.",
      hundredX: "Your design tools connect to the shared context layer. **When you make a design decision, it's visible to engineering's AI. When engineering has a constraint, your AI surfaces it** before you design something impossible.",
      impact: "The 'that's not technically feasible' feedback disappears because constraints flow in real time. Design-engineering collaboration happens through the system, not through meetings.",
      example: "A design engineer connected Figma, GitHub, Notion, and Linear through MCP. His AI knows the design system, code patterns, sprint priorities, and design principles. The walls between tools dissolve when they share a brain.",
    },
    {
      id: "engineer",
      label: "Engineering Lead",
      today: "Your architecture decisions, ADRs, and incident learnings are scattered across docs that nobody reads. New team members get answers from Stack Overflow instead of your actual decisions.",
      hundredX: "A shared architecture surface makes every technical decision AI-accessible. **New team members get answers grounded in your team's actual decisions**, not generic patterns.",
      impact: "Institutional technical knowledge stops being lost. The 'we already tried that' conversation happens through the system, not through folklore.",
      example: "A distributed engineering team built a shared architecture surface: decisions, ADRs, deployment patterns, incident learnings. New engineers get answers grounded in the team's actual decisions, not generic Stack Overflow patterns.",
    },
    {
      id: "ops",
      label: "Operations Leader",
      today: "Your team's operational knowledge is in runbooks nobody reads, Slack threads that disappear, and the heads of senior operators. When they're out, the team struggles.",
      hundredX: "A shared ops surface captures every workflow decision, exception handling pattern, and process evolution. **AI provides operational guidance grounded in your team's actual experience**, not generic playbooks.",
      impact: "Operational resilience improves because knowledge doesn't depend on specific people being available. The team performs consistently regardless of who's on shift.",
      example: "A clinical ops team built a shared patient context surface. Every team member's interactions feed a shared view. Before any encounter, AI assembles the full picture — no one walks in cold, no one asks the patient to repeat info.",
    },
    {
      id: "clinical",
      label: "Clinical Leader",
      today: "Clinical knowledge is siloed by specialty. The cardiologist doesn't see what the endocrinologist documented. Care coordination requires manual chart review and phone calls.",
      hundredX: "A shared clinical surface gives every provider AI-assembled context across specialties. **Before any encounter, the clinician sees the complete cross-specialty picture** assembled automatically.",
      impact: "Care coordination happens through the system, not through phone tag. Nothing falls through the cracks because the AI surfaces cross-specialty relevant data automatically.",
      example: "A clinical team built a shared patient surface. Every provider's interactions feed one view. Before any encounter, AI assembles the full cross-specialty picture — the cardiologist sees the endocrinologist's recent findings automatically.",
    },
  ],

  "pillar-4-ai-native-teams": [
    {
      id: "founder",
      label: "Founder / CEO",
      today: "You hired a fractional CTO who creates architecture docs but never ships code. You have strategic oversight with no execution layer. Meetings happen. Deployments don't.",
      hundredX: "You hire high-agency doers who ship to production weekly. **AI tools multiply their output**, not their meetings. Your team of 5 executes like a team of 20 because every person builds.",
      impact: "Your company moves at execution speed, not planning speed. The gap between strategy and shipping closes because the same people do both.",
      example: "A founder replaced a fractional CTO who produced roadmaps but no code with a full-time engineer who designs systems and implements them. Weekly deployments went from zero to four.",
    },
    {
      id: "pm",
      label: "Product Manager",
      today: "Your team talks about AI adoption but nobody's workflow has actually changed. Training sessions produce enthusiasm that fades by Friday. The prompt library collects dust.",
      hundredX: "Each team member practices AI refinement 20 minutes daily on real tasks. **Hands-on tutoring replaces training decks.** Within 2 weeks, the improvement is night and day.",
      impact: "AI adoption goes from 20% to 80% because the barrier drops. Your team produces more because they actually use the tools you're paying for.",
      example: "A PM stopped expecting his team to self-teach. He arranged hands-on AI tutoring sessions — someone watching each person work through real tasks. One breakthrough session per person produced permanent behavior change.",
    },
    {
      id: "designer",
      label: "Product Designer",
      today: "Half your design team experiments with AI on side projects. The other half waits for 'official AI design tools.' The gap between them widens every week.",
      hundredX: "AI adoption is non-negotiable daily practice, like a musician's scales. **The team practices 20 minutes daily on real work**, not tutorials. Within a month, everyone is productive.",
      impact: "Your design team's output doubles without adding headcount. The adoption gap closes because the practice is structured, not optional.",
      example: "A design team split organically: experimenters adopted AI in a week — generating variations and prototyping at 3x speed. After structured daily practice, the other half caught up within a month.",
    },
    {
      id: "engineer",
      label: "Engineering Lead",
      today: "Your best engineers use AI for everything. Your other engineers use it for autocomplete only. The productivity gap between them is 5x and growing. You can't hire enough senior engineers to compensate.",
      hundredX: "AI capability is a core engineering skill, not optional. **Each engineer practices AI-assisted workflows on real tasks until the skill is second nature.** The floor rises to match the ceiling.",
      impact: "Junior engineers produce senior-quality output because the knowledge base and AI cover the experience gap. Your effective engineering capacity doubles.",
      example: "A junior engineer used AI to write a test suite covering edge cases seniors typically missed. The AI helped him think more systematically. The quality was higher — because AI + judgment beats judgment alone.",
    },
    {
      id: "ops",
      label: "Operations Leader",
      today: "Your highest performers adopted AI instantly. Your process followers haven't started. Same tools, same training, same results gap. The adoption problem is a people problem.",
      hundredX: "You hire for agency and adaptability, not just domain experience. **People comfortable with their role changing every 3 months** outperform domain experts who need stability.",
      impact: "Your ops team becomes the fastest-adapting function in the company. New tools, new processes, new capabilities — adopted in days instead of quarters.",
      example: "A clinical ops team found that high-initiative coordinators became 5x more productive with AI in a month. Process followers showed near-zero adoption after 3 months. Same tools, same training, different people.",
    },
    {
      id: "clinical",
      label: "Clinical Leader",
      today: "Clinicians resist AI tools because previous 'innovations' added documentation burden without reducing it. Trust is low. Adoption requires proving value before asking for change.",
      hundredX: "AI starts with humans in the loop. Clinicians see AI-assembled context and validate it. **Trust builds through use, not through training decks.** Adoption grows because value is obvious.",
      impact: "Clinical AI adoption succeeds because it reduces burden first. Clinicians become advocates because they experience the time savings directly.",
      example: "A clinical team started with AI-assembled pre-visit context that clinicians could review and override. Within a month, clinicians were requesting more AI assistance — trust built through validated daily use.",
    },
  ],

  "pillar-2-hub-and-spoke": [
    {
      id: "founder",
      label: "Founder / CEO",
      today: "You signed a multi-year platform contract 6 months ago. A better tool launched last month. You can't switch. Your workflows, data, and team training are all entangled with one vendor.",
      hundredX: "Your platform is the hub. Every vendor tool is a replaceable spoke. **When something better launches, you swap it in days, not quarters.** Your architecture outlasts any tool decision.",
      impact: "Strategic flexibility becomes your advantage. While competitors are stuck in procurement cycles, you adopt the best tools on day one.",
      example: "A company's EHR vendor stalled a critical integration for 8 weeks. They built a bridge through their hub in 48 hours. When a better AI model launched, they swapped it with a config change.",
    },
    {
      id: "pm",
      label: "Product Manager",
      today: "Your analytics, A/B testing, and user research tools don't talk to each other. Switching any one of them means rebuilding integrations across all the others.",
      hundredX: "Your product data model is the hub. Analytics, testing, and research tools plug in as spokes. **Swapping a tool means changing a spoke, not rebuilding the pipeline.**",
      impact: "You evaluate tools by speed-to-integrate, not by vendor lock-in depth. Your product stack stays best-in-class because switching is cheap.",
      example: "A product team's analytics vendor got acquired and degraded. Because their data model was the hub, they migrated to a new provider in a week. Dashboards, experiments, and feature flags kept running.",
    },
    {
      id: "designer",
      label: "Product Designer",
      today: "Your design system is trapped in one tool. Your components, tokens, and documentation live in Figma with no way to export the logic. If you switch tools, you rebuild everything.",
      hundredX: "Your design principles and tokens are the hub. Design tools are spokes. **Your design system's logic persists regardless of which tool renders it.**",
      impact: "You adopt new design tools without losing years of design system investment. Your design infrastructure is tool-independent.",
      example: "A design engineer structured his workflow: knowledge base and design tokens in Notion (hub), Figma and code editors as spokes. When Cursor outperformed his previous editor, he switched in an afternoon.",
    },
    {
      id: "engineer",
      label: "Engineering Lead",
      today: "Your CI/CD pipeline, monitoring, and deployment are deeply coupled to one cloud provider. Moving any piece means moving everything. You're architecturally paralyzed.",
      hundredX: "Your orchestration logic and data model are the hub. Cloud services, CI/CD tools, and monitoring are spokes. **You swap infrastructure components without rebuilding core logic.**",
      impact: "Your architecture outlasts any vendor decision. Cost optimization, performance improvements, and new capabilities are configuration changes, not migrations.",
      example: "A team built their workflow engine and data model as the hub. When a better CI tool shipped, they swapped it in a day. When cloud pricing changed, they migrated the compute spoke without touching application logic.",
    },
    {
      id: "ops",
      label: "Operations Leader",
      today: "Your operational workflows are built inside vendor platforms. When the vendor changes pricing, deprecates features, or gets acquired, your operations are at risk.",
      hundredX: "Your workflow logic is the hub. Vendor tools connect as spokes. **When a vendor underperforms, you replace the spoke without disrupting operations.**",
      impact: "Operational continuity doesn't depend on vendor stability. You can respond to vendor changes in days, not months.",
      example: "An ops leader structured care coordination as the hub. The EHR handles 80% of needs — where it falls short, she builds extensions. Scheduling and communication tools upgrade independently without workflow disruption.",
    },
    {
      id: "clinical",
      label: "Clinical Leader",
      today: "Your EHR dictates your workflows. Clinical processes are shaped by what the software allows, not what patients need. When you need to change a workflow, IT says '6 months.'",
      hundredX: "Your care coordination logic is the hub. The EHR is a spoke. **Clinical workflows are designed for patient outcomes**, not EHR limitations. When the EHR falls short, you build around it.",
      impact: "Clinical workflows serve patients, not vendors. New care models deploy in days because your architecture is designed for clinical flexibility.",
      example: "A clinical team built custom interfaces reading from their own hub. The EHR handles 80% of needs. Where it falls short, they build extensions. A new care model deployed in 48 hours — not the typical 6-month IT project.",
    },
  ],

  "building-moat-at-scale": [
    {
      id: "founder",
      label: "Founder / CEO",
      today: "Your company's knowledge is scattered across 40 Notion pages, 12 Slack channels, and a few people's heads. When they leave, context walks out the door.",
      hundredX: "Every team interaction generates knowledge automatically. AI synthesizes it into the shared base. **After 12 months, you have 5,000+ artifacts no competitor can replicate.** The moat compounds daily.",
      impact: "Your company's intelligence becomes a genuine competitive moat. Competitors who adopt the same tools are still 12+ months behind on context.",
      example: "A company built a knowledge loop: calls flow through Granola → AI synthesizes evidence → insights deposit into Notion → any team member's AI draws from the full base. After 6 months, the output quality gap versus competitors was visible in every deliverable.",
    },
    {
      id: "pm",
      label: "Product Manager",
      today: "Product knowledge lives in individual PMs' heads. When someone changes roles, their research and context are effectively lost. Each new PM starts from scratch.",
      hundredX: "Every customer call, research finding, and product decision enriches a shared base. **New PMs get AI context equivalent to years of institutional knowledge** from day one.",
      impact: "Product knowledge compounds across people, not just within individuals. PM turnover stops being a knowledge crisis.",
      example: "A PM structures every call note with 'My analysis' (personal) and 'Evidence for the base' (facts and data). The second section enriches the team's knowledge automatically. She doesn't do extra work — she structures the same work to compound.",
    },
    {
      id: "designer",
      label: "Product Designer",
      today: "Design decisions are made and forgotten. Project learnings live in individual designers' memories. New projects start from zero instead of building on what you've already learned.",
      hundredX: "Every design decision, client feedback pattern, and creative direction is captured. **New projects start with accumulated wisdom from every previous project**, not just the assigned designer's memory.",
      impact: "Design quality compounds across the organization. Junior designers produce senior-level work because the knowledge base carries the team's collective taste.",
      example: "A design agency scaled their creative process across 8 designers. Project learnings, client preferences, and aesthetic evolution all feed one base. New projects start with wisdom from every previous project — not just the assigned designer's.",
    },
    {
      id: "engineer",
      label: "Engineering Lead",
      today: "Architecture decisions are documented in ADRs nobody reads. Incident learnings are discussed once and forgotten. New engineers repeat the same mistakes previous engineers already solved.",
      hundredX: "Architecture decisions, incident learnings, and technical patterns all feed the shared base. **AI prevents repeated mistakes by surfacing relevant precedent** before anyone makes the same error twice.",
      impact: "Engineering knowledge compounds across the team. The same mistake never happens twice because the system remembers what individuals forget.",
      example: "A team's engineering knowledge base captures every ADR, incident postmortem, and technical decision. When an engineer proposes a refactor, AI surfaces 'we tried this in Q2 — here's what happened.' The system has institutional memory.",
    },
    {
      id: "ops",
      label: "Operations Leader",
      today: "Operational knowledge is tribal. Senior operators know why processes work the way they do. Juniors follow procedures without understanding the reasoning. When seniors leave, the reasoning goes with them.",
      hundredX: "Every workflow decision and process evolution is captured with reasoning. **Juniors understand the 'why' because the knowledge base carries it.** Operational quality doesn't depend on specific people.",
      impact: "Operations become resilient to turnover. New hires reach full effectiveness 3x faster because institutional reasoning is accessible, not just procedures.",
      example: "An ops team encoded not just procedures but the reasoning behind them — why this escalation path, why this threshold, what happened when we tried it differently. New hires' AI explains the 'why' alongside the 'what.'",
    },
    {
      id: "clinical",
      label: "Clinical Leader",
      today: "Clinical knowledge is locked in individual providers' experience. A new hire needs 2–3 years to accumulate the contextual understanding that makes clinical decisions nuanced.",
      hundredX: "Every patient encounter enriches the shared clinical knowledge base. **A new hire's AI has the context equivalent to 3 years of institutional experience** from their first day.",
      impact: "Clinical quality becomes consistent across providers. Experienced clinicians' knowledge scales to the whole team without requiring their time for every consult.",
      example: "A healthcare org scaled their knowledge base across 50 providers. Every encounter enriches the base. After 6 months, a new hire's AI has context equivalent to 3 years at the organization — care consistency improved measurably.",
    },
  ],

  "pillar-5-performance-standards": [
    {
      id: "founder",
      label: "Founder / CEO",
      today: "Your best people produce work in hours that used to take weeks. Instead of celebrating, your organization questions the quality. Your culture still equates time invested with rigor.",
      hundredX: "You measure shipped outcomes per week, not hours invested. **Performance is judged by operational impact**, not by visible effort. Your culture rewards the result, not the performance of working hard.",
      impact: "Your best people stay because their speed is valued, not questioned. You attract AI-native talent that your competitors can't, because you're the company that gets it.",
      example: "A startup stopped tracking hours and started tracking 'shipped outcomes per week.' Every team member ships something live by Friday. Actual output — features, decisions, experiments — tripled in the first quarter.",
    },
    {
      id: "pm",
      label: "Product Manager",
      today: "You produce a brief in 40 minutes with AI that's better than what used to take 3 days. Your manager's response: 'Did you actually research this?' Fast work triggers suspicion, not praise.",
      hundredX: "You articulate your process: knowledge base context, AI assembly, and the 3 judgment calls you made. **Quality is proven by the output and reasoning**, not by the calendar time behind it.",
      impact: "You produce 5x more briefs at higher quality. Your career advances because output quality speaks for itself, and you can explain why it's good.",
      example: "A PM learned to explain her process: 'I pulled persona research and competitive context from the knowledge base. AI drafted. I spent 40 minutes on judgment calls — positioning, prioritization, and user conflict points.' Trust earned.",
    },
    {
      id: "designer",
      label: "Product Designer",
      today: "You generate 5 directions in a morning instead of spending 3 days on 1. Your manager thinks you didn't think hard enough. The cultural assumption: fast design = lazy design.",
      hundredX: "You present 5 directions evaluated against persona data with evidence for the top 2. **Quality goes up because you tested more hypotheses.** Speed becomes a creative advantage, not a liability.",
      impact: "Your design practice evolves from single-bet to multi-hypothesis. Quality improves because you explore more of the solution space in less time.",
      example: "A designer generates 5 homepage directions in a morning, evaluates each against persona data and constraints, and presents the 2 strongest with evidence. Quality went up because she tested more hypotheses. Time went down 60%.",
    },
    {
      id: "engineer",
      label: "Engineering Lead",
      today: "A junior engineer ships a feature matching senior quality. The team assumes it's copied or AI-generated in a dismissive sense. The quality is higher — and that's the problem.",
      hundredX: "AI-assisted development is the baseline expectation. **Juniors producing senior-quality output is the goal, not an anomaly.** You evaluate the code, not the author's seniority.",
      impact: "Your effective engineering capacity doubles because juniors contribute at a higher level. The senior/junior gap narrows on output quality and widens on architectural judgment.",
      example: "A junior used AI to write tests covering edge cases seniors missed. The AI helped him think more systematically. The tech lead evaluated the tests on quality alone — they were excellent. The team adopted the practice.",
    },
    {
      id: "ops",
      label: "Operations Leader",
      today: "Your team implements a process improvement in 2 days that used to take 3 weeks. Leadership asks for 'more due diligence' — not because the result is wrong, but because the speed feels wrong.",
      hundredX: "Process improvements are measured by outcomes: error rates, throughput, cost. **Speed is a feature, not a risk flag.** The team that iterates fastest wins.",
      impact: "Your ops team becomes known for execution speed. Continuous improvement happens weekly instead of quarterly because the team isn't penalized for moving fast.",
      example: "An ops team deployed a workflow improvement in 2 days. Instead of questioning the speed, leadership asked 'what were the results?' Error rate dropped 40%. The team now ships improvements weekly.",
    },
    {
      id: "clinical",
      label: "Clinical Leader",
      today: "AI-assisted clinical notes are completed in 5 minutes instead of 40. Compliance flags them for review because they're 'suspiciously fast.' The same notes would pass if they took longer.",
      hundredX: "Documentation quality is measured by completeness, accuracy, and clinical utility — not by time spent. **AI-assisted notes are the standard**, not the exception to be scrutinized.",
      impact: "Clinicians gain 35 minutes per encounter for actual patient care. Documentation quality improves because AI ensures completeness that hurried manual notes miss.",
      example: "AI-assisted clinical notes were more complete and more structured than manual ones. Once compliance evaluated content quality instead of completion speed, they became the preferred documentation method.",
    },
  ],
};
