// Millie's word bank and persona: Princess Donut, a doodle cat who is
// certain she is royalty, runs the betting desk for a 9-year-old who loves
// cats and dogs. Words are cat, dog and pet themed, including the family's
// own animals and famous cartoon pets.
import type { Entry, Rank, Doodle } from "./engine";

export const MILLIE_BANK: Entry[] = [
  // Level 1
  { w: "bark", l: 1, p: "letter patterns", s: "Hatchi gives the postie one huge bark, then hides behind Mum.", h: "The loud sound a dog makes. Also the rough skin on a tree.", d: "ar", t: "Listen for the ar in the middle, like a pirate dog saying b-ar-k." },
  { w: "basket", l: 1, p: "unstressed vowels", s: "Kumo sleeps in the dog basket, and Hatchi is too polite to say anything.", h: "A woven box for a pet to sleep in.", d: "ket", t: "It sounds like bask-it, but the lazy vowel is really an e. Say bas-KET loudly to hear it." },
  { w: "Bingo", l: 1, p: "cartoon pets", s: "Bingo does her squeaky voice until the whole family cracks up.", h: "The younger red heeler sister in that Australian puppy cartoon.", d: "ngo", t: "Two little words hide inside: a bin and a go. Bin plus go, so it ends ngo with no e." },
  { w: "Bluey", l: 1, p: "cartoon pets", s: "Bluey turns one cardboard box into an entire adventure.", h: "The cartoon Australian heeler pup who makes up a game for everything.", d: "ey", t: "Take the colour of the sky, then pop a y on the end. Blue plus y, and the e stays in the middle." },
  { w: "Bolt", l: 1, p: "cartoon pets", s: "Bolt tries out his super bark. The cat yawns.", h: "The white cartoon shepherd pup who thinks he has super powers.", d: "lt", t: "The l is easy to miss when you say it fast. Zap it in like a lightning bolt: b, o, l, t." },
  { w: "bone", l: 1, p: "silent letters", s: "Barley buried a bone in the garden, then forgot which garden.", h: "A hard white part inside you that helps you stand up. Dogs love to chew them.", d: "e", t: "The e on the end is silent but magic. It makes the o say its own name, so it is not bon." },
  { w: "bowl", l: 1, p: "hidden letters", s: "Kumo tips his bowl over, then complains that it is empty.", h: "A round dish that holds food or water.", d: "owl", t: "There is an owl hiding at the end. An owl in the food dish, and it is ow, not oa." },
  { w: "claws", l: 1, p: "letter patterns", s: "Norman keeps his claws sharp for the sofa, never for cuddles.", h: "The sharp hooks on a cat's toes. Not part of a sentence.", d: "aw", t: "Same aw as in paws. Aw for the sound, and the sofa says ow." },
  { w: "cuddle", l: 1, p: "double letters", s: "Rosie wanted a cuddle at six in the morning. Dad said no. Rosie won.", h: "A warm hug in your arms.", d: "dd", t: "It takes two arms, so it takes two d's. Finish with a quiet e that says nothing." },
  { w: "fetch", l: 1, p: "letter patterns", s: "Barley will fetch the ball. Giving it back is not part of his plan.", h: "To run after something and bring it back.", d: "tch", t: "After a short vowel the ch needs a t to help it catch. Fetch, catch, match." },
  { w: "fluffy", l: 1, p: "double letters", s: "Mable is so fluffy she looks like a cloud with legs and a bark.", h: "Soft, light and covered in lots of fur.", d: "ff", t: "Extra fluff needs extra f. Two f's in the middle, then y on the end." },
  { w: "furry", l: 1, p: "double letters", s: "Mr Fluffington is a furry pillow with a very grumpy face.", h: "Covered in soft, thick animal hair.", d: "rr", t: "Fur plus ry needs two r's, one for each fuzzy side. Then y, never ee." },
  { w: "jump", l: 1, p: "letter patterns", s: "Scooby can jump over the fence, but only if sausages are involved.", h: "To spring up off the ground with both feet.", d: "j", t: "It starts with j, even though the sound could trick you into a g. J for joy, jam and jumping dogs." },
  { w: "kitten", l: 1, p: "double letters", s: "Kumo was a kitten who slept inside a shoe. Now he sleeps on Dad's face.", h: "A baby cat.", d: "tt", t: "They always arrive in twos, so the t comes twice too. It ends in en, not in." },
  { w: "Kumo", l: 1, p: "pet names", s: "Kumo appears out of nowhere, stares at nothing, then vanishes again.", h: "The mysterious cat with a Japanese name that means cloud.", d: "Ku", t: "It sounds like coo, but it starts with K and u. Mystery cats begin with K: Ku plus mo." },
  { w: "leash", l: 1, p: "letter patterns", s: "Hatchi grabbed his own leash and dragged Mum all the way to the park.", h: "The strap you clip on to walk a dog.", d: "ea", t: "It has ea in the middle like eat and sea, then finishes with sh: lea plus sh." },
  { w: "lick", l: 1, p: "letter patterns", s: "One lick from Mable and your face is officially washed.", h: "To wipe your tongue over something.", d: "ck", t: "Short vowel words end in ck, not just k. Lick, kick, stick." },
  { w: "meow", l: 1, p: "letter patterns", s: "Norman has one meow, and it means feed me right now.", h: "The noise a cat makes when it wants dinner.", d: "eo", t: "Cats say ee then ow, so the e comes before the o. M-e-o-w, in that order." },
  { w: "milk", l: 1, p: "letter patterns", s: "Donut stole the milk and left tiny white paw prints as a confession.", h: "The white drink that comes from a cow.", d: "lk", t: "Say the l out loud. It is mi-L-k, not miwk. The l is doing its job." },
  { w: "Odie", l: 1, p: "cartoon pets", s: "Odie washes Garfield's whole face in one enormous slurp.", h: "The goofy beagle with the huge tongue who lives with that orange cat.", d: "ie", t: "Only four letters, and the last two are ie, not ee. O, d, then the same ie that ends Rosie and Lassie." },
  { w: "paws", l: 1, p: "letter patterns", s: "Norman has four white paws and exactly zero manners.", h: "The soft feet an animal walks on. Not a short stop or break.", d: "aw", t: "They say aw in the middle, just like the aw sound you make when you see them." },
  { w: "Pluto", l: 1, p: "cartoon pets", s: "Pluto barks at his own tail and loses every single time.", h: "Mickey Mouse's yellow pet hound, and also a tiny far away dwarf planet.", d: "u", t: "It sounds like Ploo, but there is only one u doing all that work. No oo allowed." },
  { w: "puppy", l: 1, p: "double letters", s: "Barley was a puppy once. He ate one slipper and blamed the cat.", h: "A very young dog, only a few weeks old.", d: "pp", t: "Two p's in the middle, one for each floppy ear. Then y for that yappy little voice." },
  { w: "purr", l: 1, p: "double letters", s: "Scratch Donut's chin and she will purr like a small tractor.", h: "The happy rumble a cat makes in its throat.", d: "rr", t: "A cat keeps the sound going, so the r goes on twice. Two r's, no more." },
  { w: "sleepy", l: 1, p: "double letters", s: "Mable gets sleepy the second the walk ends, then wide awake at bedtime.", h: "Ready for a nap, with heavy eyes.", d: "ee", t: "Double e for two closed eyes. Then y, because it is sleep plus y." },
  { w: "sniff", l: 1, p: "double letters", s: "Rosie must sniff every lamppost on the street. Every single one.", h: "To breathe in through your nose to smell.", d: "ff", t: "One is never enough for a dog nose, so the f comes twice at the end." },
  { w: "tail", l: 1, p: "letter patterns", s: "Rosie wags her tail so hard she knocks the bin over.", h: "The wagging part at the back end of a dog. Not a story you read.", d: "ai", t: "It is ai, not ay. The a goes first and the i follows behind, like a dog on a lead." },
  { w: "treat", l: 1, p: "letter patterns", s: "Mable heard the treat bag open from three rooms away, through a shut door.", h: "A tasty little snack given as a reward.", d: "ea", t: "The word eat is hiding at the end. Tr plus eat, because dogs eat them in one gulp." },
  { w: "wag", l: 1, p: "letter patterns", s: "Barley starts to wag before you even finish saying his name.", h: "To flick a tail from side to side in joy.", d: "a", t: "Just three sounds: w-a-g, with one g at the end. When the tail keeps going you double it: wagging." },
  { w: "walk", l: 1, p: "silent letters", s: "Say the word walk and Barley does eleven happy spins.", h: "To go along on your feet, not running.", d: "al", t: "There is a sneaky l in there that says nothing at all. W-a-silent L-k." },
  // Level 2
  { w: "Barley", l: 2, p: "pet names", s: "Barley chased his own tail and fell straight into the paddling pool.", h: "The goofiest dog in the house, named after a crop that farmers grow.", d: "ley", t: "Bar plus ley. Only ONE l, and the e comes before the y, just like Bluey." },
  { w: "beagle", l: 2, p: "letter patterns", s: "Snoopy is the most famous beagle in the world, and he sleeps on his roof.", h: "A small hound with long ears and a brilliant nose.", d: "ea", t: "There is an EAGLE hiding inside: b-EAGLE. The EA says EE." },
  { w: "blanket", l: 2, p: "letter patterns", s: "Mable dragged the blanket off the couch and built herself a nest.", h: "A soft cover for keeping warm in bed.", d: "ket", t: "BLANK plus ET, like bucKET and pocKET. Mable's is no longer blank, it is all fur." },
  { w: "collar", l: 2, p: "double letters", s: "Rosie's collar has a bell, so every squirrel gets a fair warning.", h: "A band that goes round a pet's neck.", d: "ll", t: "Two l's in the middle, and it ends in ar, not er. Like a star round the neck." },
  { w: "digging", l: 2, p: "ing doubling", s: "Rosie is digging a tunnel to the neighbour's garden. She is halfway there.", h: "Making a hole in the ground.", d: "gg", t: "DIG plus G plus ING. Short word, one vowel, so double the last letter before ING." },
  { w: "Donut", l: 2, p: "pet names", s: "Princess Donut yawns on her throne of warm, clean laundry.", h: "The royal cat, named after a sweet ring-shaped treat.", d: "nu", t: "Do plus nut, like a nut you can eat. One n is plenty, because there is only one princess." },
  { w: "foxes", l: 2, p: "plurals", s: "Two foxes sat on the fence and watched Hatchi bark bravely at a bin.", h: "More than one bushy-tailed wild animal.", d: "es", t: "Words ending in X need ES so you can hear the plural: box-es, fox-es, six-es." },
  { w: "gentle", l: 2, p: "soft c and g", s: "Be gentle with Mr Fluffington. He is mostly fluff and opinions.", h: "Soft and careful, not rough.", d: "ge", t: "G before E says J: GEntle. Then the quiet LE on the end, said soft like a whisper." },
  { w: "ginger", l: 2, p: "soft c and g", s: "A ginger cat sat in Norman's spot. Norman has not forgiven anyone since.", h: "Orange-red in colour, like a spicy root.", d: "gi", t: "G before i says j: GInger. The second g goes soft too, because an e comes straight after it." },
  { w: "Gromit", l: 2, p: "cartoon pets", s: "Gromit rolls his eyes because Wallace forgot the cheese again.", h: "The clever silent dog made of plasticine who fixes rockets and knits jumpers.", d: "it", t: "One m only, then a tiny word on the end: it. Grom plus it, and it finishes with it, never et." },
  { w: "Hatchi", l: 2, p: "pet names", s: "Hatchi waits by the front door for hours, just in case you come home early.", h: "The most loyal dog in the family, always on guard by the door.", d: "tch", t: "There is a caTCH in the middle: t, c, h all in a row, like the hatch on a boat. Say hat-chee and hear the hidden t." },
  { w: "husky", l: 2, p: "letter patterns", s: "A husky like Balto can pull a sled through a snowstorm. Hatchi cannot pull a sock.", h: "A thick-furred sled dog from cold places.", d: "sky", t: "It ends in KY with no E. The Y does the E's job, and look, the SKY is in there." },
  { w: "kennel", l: 2, p: "double letters", s: "Barley has a kennel in the garden. He sleeps in Dad's bed.", h: "A little hut outside where a dog can rest.", d: "nn", t: "Two N's in the middle and EL on the end: ke-NN-el. Two N's, one very spoiled dog." },
  { w: "kibble", l: 2, p: "double letters", s: "Norman stared at his kibble like it had insulted his family.", h: "Dry crunchy pellets that pets eat.", d: "bb", t: "Two B's, then LE: ki-BB-le. Like pebble and bubble. Little dry pebbles in a bowl." },
  { w: "Lassie", l: 2, p: "cartoon pets", s: "Lassie sprints ten miles home to fetch help. Hatchi sprints to the fridge.", h: "The brave rough collie who is famous for coming home.", d: "ssie", t: "Double s in the middle, then ie on the end just like Rosie. Not ee, ie." },
  { w: "Mable", l: 2, p: "pet names", s: "Mable howls like the world is ending, just because her bowl is nearly empty.", h: "The most dramatic dog alive, who treats every small thing as an emergency.", d: "le", t: "She ends with a sleepy le, not el. Ma plus b plus le, like table and cradle." },
  { w: "muzzle", l: 2, p: "double letters", s: "Barley pushed his muzzle into the cake box and came out wearing icing.", h: "The nose and mouth part of a dog's face.", d: "zz", t: "Two Z's buzzing in the middle, then LE: mu-ZZ-le. Like puzzle and dazzle." },
  { w: "naughty", l: 2, p: "letter patterns", s: "Who was naughty? All four dogs looked straight at Mable.", h: "Badly behaved and cheeky.", d: "augh", t: "N-AUGH-TY. The AUGH says OR, the same as cAUGHt and tAUGHt. Cheeky dogs get caught." },
  { w: "Norman", l: 2, p: "pet names", s: "Norman is shaped like a loaf of bread and grumpy like thunder.", h: "The grumpy cat with a very ordinary human name.", d: "man", t: "He sounds like Nor-mun, but he ends in man, like a person. Nor plus man, because he is a tiny angry gentleman." },
  { w: "poodle", l: 2, p: "letter patterns", s: "The poodle next door has a better haircut than anyone in our family.", h: "A dog breed with curly fluffy fur.", d: "oo", t: "Double O, then DLE: POO-dle. It rhymes with noodle. A curly noodle on legs." },
  { w: "pounce", l: 2, p: "soft c and g", s: "Donut waits behind the door, ready to pounce on a stray sock.", h: "To jump suddenly onto something.", d: "ce", t: "It ends in CE, not se. The C does the hissing: poun-CE. Same as danCE and prinCE." },
  { w: "puppies", l: 2, p: "plurals", s: "Six puppies, one basket, zero peace.", h: "More than one baby dog.", d: "ies", t: "One puppy, lots of puppies. The Y gets shy, hides, and turns into IES." },
  { w: "rescue", l: 2, p: "letter patterns", s: "We had to rescue Mable from the laundry basket. Again.", h: "To save someone from danger.", d: "cue", t: "RES plus CUE. It ends like a snooker CUE, never cew. Every rescue needs a CUE." },
  { w: "Rosie", l: 2, p: "pet names", s: "Rosie says hello by licking the postman's shoes, every single day.", h: "The sweetest dog in the house, named after a pink garden flower.", d: "ie", t: "She ends with i before e, like a little smile. Ros plus i-e, never e-y." },
  { w: "running", l: 2, p: "ing doubling", s: "Hatchi is running in his sleep again. His legs have no idea he is in bed.", h: "Moving fast on your legs.", d: "nn", t: "RUN plus N plus ING. Double the N. One N gives runing, and nobody has ever runed anywhere." },
  { w: "Scooby", l: 2, p: "cartoon pets", s: "Scooby will face any ghost, as long as there is a giant sandwich in it.", h: "The big brown Great Dane who is scared of spooks but loves snacks.", d: "oo", t: "Double o, like two big scared eyes staring at a ghost. His famous shout ends in Doo, and Doo has oo, so he does too." },
  { w: "scratch", l: 2, p: "letter patterns", s: "Do not scratch the couch, Kumo. Kumo scratched the couch.", h: "To drag claws across something.", d: "tch", t: "Short vowel words end in TCH: caTCH, maTCH, scraTCH. The T sneaks in before the CH." },
  { w: "Snoopy", l: 2, p: "cartoon pets", s: "Snoopy sleeps on the roof of his kennel and never once falls off.", h: "The white beagle with black ears who dreams of being a flying ace.", d: "oo", t: "He snoozes on a roof, and roof has double o. So does his name: Sn, oo, py." },
  { w: "snuggle", l: 2, p: "double letters", s: "Rosie will snuggle anyone who sits still for three whole seconds.", h: "To curl up close for warmth and cuddles.", d: "gg", t: "Two G's, then the quiet LE: snu-GG-le. Same shape as wriggle and giggle." },
  { w: "squeaky", l: 2, p: "letter patterns", s: "Mable's squeaky toy went off at five in the morning, eleven times.", h: "Making a high thin noise, like a mouse toy.", d: "squ", t: "Q never goes anywhere without U: SQU. Then EAK, then Y. SQU-EAK-Y." },
  { w: "tabby", l: 2, p: "double letters", s: "Kumo is a tabby, and he is certain that makes him a tiger.", h: "A cat with a stripy coat and often an M on its forehead.", d: "bby", t: "A short A needs two B's before the Y: ta-BB-y. Like chubby and hobby." },
  { w: "tongue", l: 2, p: "silent letters", s: "Hatchi's tongue hangs out even when he is fast asleep.", h: "The pink thing in your mouth that tastes your food.", d: "gue", t: "It ends in GUE, like leaGUE. The U and E say nothing. Hatchi's never says nothing." },
  { w: "wagging", l: 2, p: "ing doubling", s: "Barley's tail was wagging so hard it cleared the whole coffee table.", h: "Swishing a tail back and forth with joy.", d: "gg", t: "WAG plus G plus ING. Double the G, or you get waging, which no tail has ever done." },
  { w: "whiskers", l: 2, p: "letter patterns", s: "Kumo's whiskers are longer than his patience.", h: "The long stiff hairs on a cat's face.", d: "wh", t: "Starts with WH, like WHy and WHen. Kumo's WH is always asking WHere dinner is." },
  // Level 3
  { w: "adopted", l: 3, p: "letter patterns", s: "We adopted Rosie. Then Rosie adopted the entire sofa.", h: "Took an animal home to be part of your family for good.", d: "pted", t: "Just add ED to the end. Do not double the t: adopTED, one t only." },
  { w: "beautiful", l: 3, p: "letter patterns", s: "Kumo sat in the sunbeam looking beautiful and refusing to move for anyone.", h: "Really lovely to look at.", d: "eau", t: "Big Ears Are Useful: B-E-A-U. That is the tricky start." },
  { w: "biscuit", l: 3, p: "silent letters", s: "Hatchi can hear a biscuit tin open from the other end of town.", h: "A crunchy little treat, great for dogs and for dunking.", d: "cui", t: "After the c sneaks in a silent u: bis-C-U-it. The u says nothing at all." },
  { w: "brilliant", l: 3, p: "double letters", s: "Mable had a brilliant plan. The plan was to eat the plan.", h: "Super clever, or shining really bright.", d: "ll", t: "Double l in the middle, like two bright bulbs: bri-LL-iant." },
  { w: "Cheshire", l: 3, p: "cartoon pets", s: "Cheshire grinned, then vanished and left just the grin behind.", h: "The grinning cat in Wonderland who fades away until only his smile is left.", d: "eshire", t: "Ch plus eshire. There are two h's, one after the c and one before the ire, and it ends ire like fire even though it sounds like er." },
  { w: "Clifford", l: 3, p: "cartoon pets", s: "Clifford wagged his tail once and knocked over a bus.", h: "The giant red dog from the storybooks who is taller than a house.", d: "fford", t: "A cliff plus a Ford car. Cliff brings double f, then ord like a Ford, never urd." },
  { w: "cushion", l: 3, p: "letter patterns", s: "Norman claimed the best cushion in the house and will not be moved.", h: "A soft pad you sit on.", d: "shio", t: "cu-SHI-ON. It is SHI then ON, not TION. Hear the SH, then land on the ION." },
  { w: "delicious", l: 3, p: "soft c and g", s: "Hatchi believes anything that hits the floor is instantly delicious.", h: "Tasting so good you want the whole bowl.", d: "cious", t: "This c hisses like SH. It sounds like lish, but you write CIOUS." },
  { w: "enormous", l: 3, p: "letter patterns", s: "An enormous cat called Norman is sitting on my homework again.", h: "Really, really huge.", d: "ous", t: "It ends OUS, like a mouse with no e. Big words love an OUS ending." },
  { w: "exercise", l: 3, p: "letter patterns", s: "Barley's idea of exercise is one lap of the garden, then a long nap.", h: "Moving your body to keep it fit and strong.", d: "erc", t: "An x, then er, then a c: e-X-e-R-C-ise. No s hiding in the middle." },
  { w: "favourite", l: 3, p: "our words", s: "Barley's favourite game is stealing one sock and running for the door.", h: "The one you like best of all.", d: "our", t: "It is OUR pick, so keep the u in: fav-OUR-ite." },
  { w: "Fluffington", l: 3, p: "pet names", s: "Mr Fluffington sat on the keyboard and typed his own name: Fluffington.", h: "The very posh second name of the family's puffiest cat.", d: "ff", t: "Break the posh name into three bits: FLUFF with two f's, then ing, then ton like a little town." },
  { w: "friendly", l: 3, p: "ie / ei", s: "Hatchi is so friendly that even the postman gets a cuddle.", h: "Kind and warm to everyone you meet.", d: "ie", t: "There is an END in it with an i before: fri-END-ly." },
  { w: "Garfield", l: 3, p: "cartoon pets", s: "Garfield ate the whole lasagne, then asked what was for dinner.", h: "The fat orange comic cat who hates Mondays and loves lasagne.", d: "field", t: "Gar plus field. A field of lasagne, and every field has i before e." },
  { w: "gorgeous", l: 3, p: "soft c and g", s: "Mable rolled in mud and still thought she looked absolutely gorgeous.", h: "So lovely that people stop and stare.", d: "geous", t: "Keep the e after the g so the g stays soft: G-E-O-U-S." },
  { w: "greyhound", l: 3, p: "letter patterns", s: "A greyhound zoomed past Kumo so fast that his whiskers blew backwards.", h: "A slim super fast dog built like a rocket on legs.", d: "ey", t: "Here it is grEY with an e, then hound. Grey dogs, never gray ones." },
  { w: "labrador", l: 3, p: "unstressed vowels", s: "Hatchi told the labrador that the couch was already taken, thank you.", h: "A big friendly dog, often yellow, black or chocolate.", d: "rador", t: "Lab plus RADOR. The sleepy vowel after the b is an a, not an o: lab-RA-dor." },
  { w: "medicine", l: 3, p: "soft c and g", s: "We hide Rosie's medicine in a lump of cheese. She eats the cheese and leaves the medicine.", h: "Something you take to help you get well again.", d: "ci", t: "Medi plus CINE. The c says s because an i comes next." },
  { w: "mischief", l: 3, p: "ie / ei", s: "Donut caused so much mischief that the tinsel is now in the fish tank.", h: "Playful naughty trouble that makes grown-ups sigh.", d: "ie", t: "The chief of the gang has IE, and so does this word. I before E." },
  { w: "muscle", l: 3, p: "silent letters", s: "Norman flexed one muscle, got tired, and went straight back to sleep.", h: "The strong stretchy part inside you that makes your body move.", d: "sc", t: "There is a silent c. You can hear it wake up in muscular: mus-Cular." },
  { w: "neighbour", l: 3, p: "ie / ei", s: "Our neighbour's cat pops in for lunch with Norman every single day.", h: "The person who lives right next door to you.", d: "eigh", t: "Neigh like a horse, then bour. E comes before i: n-E-I-G-H." },
  { w: "Persian", l: 3, p: "letter patterns", s: "Mable barked at a Persian cat that looked exactly like a grumpy cushion.", h: "A fluffy flat-faced cat with a very long coat.", d: "sian", t: "The ending sounds like shun but you write SIAN. Per plus sian." },
  { w: "recognise", l: 3, p: "hidden letters", s: "Kumo can recognise a tuna tin opening from three rooms away.", h: "To know something the moment you see or hear it again.", d: "gn", t: "There is a hidden g. Say re-COG-nise to hear it, then finish with ISE." },
  { w: "separate", l: 3, p: "unstressed vowels", s: "We had to separate Norman and Kumo before the great sofa war began.", h: "To move things apart so they are not together.", d: "para", t: "There is A RAT in sep-A-RAT-e. Say the rat out loud and the middle a can never turn into an e." },
  { w: "Siamese", l: 3, p: "letter patterns", s: "Norman says the Siamese cat next door never, ever stops talking.", h: "A slim pale cat with dark ears, face, paws and tail.", d: "iam", t: "The old country Siam hides at the start: S-i-a-m, then ese like Chinese." },
  { w: "spaniel", l: 3, p: "letter patterns", s: "Barley met a spaniel with ears so long they mopped the kitchen floor.", h: "A dog with long droopy ears and a lovely wavy coat.", d: "iel", t: "It ends I-E-L, not just EL. Say SPAN, then finish it like the name Daniel." },
  { w: "terrier", l: 3, p: "double letters", s: "Rosie is a terrier, and every terrier is certain it owns the whole street.", h: "A small bouncy kind of dog that loves digging holes.", d: "rr", t: "Two r's in the middle, like two ears on one very busy dog: te-RR-ier." },
  { w: "wriggle", l: 3, p: "silent letters", s: "Donut can wriggle out of any cuddle in under two seconds.", h: "To twist and squirm about like a wiggly worm in the grass.", d: "wr", t: "Silent w at the start, like in write, wrong and wrap. Then two g's in the middle: wri-GG-le." },
  // Level 4
  { w: "adorable", l: 4, p: "letter patterns", s: "Mable snoring upside down is completely adorable, and completely loud.", h: "So cute you want to squeeze it.", d: "able", t: "Take ADORE, throw away the e, then add ABLE. If you adore her, she is ABLE to be adored." },
  { w: "affectionate", l: 4, p: "double letters", s: "Rosie is so affectionate she licks your face before you are even awake.", h: "Full of cuddles and love for someone.", d: "ffection", t: "Double f, because one f is never enough love. Then it is AFFECTION plus ATE." },
  { w: "chihuahua", l: 4, p: "letter patterns", s: "The chihuahua next door barked at Rosie, who is ten times her size. Rosie apologised.", h: "A tiny dog from Mexico that shivers and thinks it is huge.", d: "huahua", t: "Chant it: CHI hua hua. Say HUA twice, like a tiny dog going hua hua, and you will never lose your place." },
  { w: "companion", l: 4, p: "unstressed vowels", s: "Snoopy picked one companion for life: Woodstock, a very small yellow bird.", h: "A friend who goes everywhere with you.", d: "panion", t: "COM plus PAN plus ION. A true pal shares your PAN of dinner, then you add ION like in onion." },
  { w: "curiosity", l: 4, p: "letter patterns", s: "Curiosity got Jiji stuck inside the laundry basket again.", h: "The itch to find out what something is.", d: "iosi", t: "Start with CURIOUS, drop the u, add ITY. The o stays behind: curi-OSI-ty." },
  { w: "dachshund", l: 4, p: "hidden letters", s: "Hatchi met a dachshund who was longer than the whole sofa.", h: "A long sausage-shaped sniffer dog with very short legs.", d: "chsh", t: "It is two German words squashed together: DACHS plus HUND. That gives you the silly middle chsh, and the h inside ch says nothing, so ch sounds like k." },
  { w: "dalmatian", l: 4, p: "tion words", s: "A dalmatian has more spots than Kumo has whiskers.", h: "A white dog covered in black spots, famous at fire stations.", d: "tian", t: "It ends TIAN, not TION. There is no o anywhere, so spot the a: dalma-TI-AN." },
  { w: "disappeared", l: 4, p: "double letters", s: "The last biscuit disappeared, and Hatchi looks completely innocent.", h: "Vanished and nowhere to be found.", d: "sapp", t: "One s, then two p's: DIS plus APPEAR plus ED. The APPEAR half keeps its double p and its EAR." },
  { w: "energetic", l: 4, p: "soft c and g", s: "Bluey is so energetic she wears out three tennis balls a day.", h: "Bursting with go and never sitting still.", d: "getic", t: "The g says j because an e follows it, and the ending is a hard c, not a k: GET-IC." },
  { w: "ferocious", l: 4, p: "soft c and g", s: "Princess Donut looks ferocious, then falls asleep inside a shoe.", h: "Fierce, growly and ready to pounce.", d: "cious", t: "That SH sound is really CIOUS, like delicious. C plus IOUS, never sh." },
  { w: "magnificent", l: 4, p: "soft c and g", s: "Mr Fluffington sat on the windowsill looking magnificent, then fell off.", h: "Really grand and impressive to look at.", d: "cent", t: "It ends with CENT, like a coin, not sent. A magnificent cat is worth every CENT." },
  { w: "mysterious", l: 4, p: "hidden letters", s: "Something mysterious ate the sausages, and Kumo looks very guilty.", h: "Strange and very hard to explain.", d: "yste", t: "The first vowel sound is a y, not an i. Write MYSTERY, then swap that last y for IOUS." },
  { w: "obedient", l: 4, p: "ie / ei", s: "Scooby is obedient right up until somebody mentions snacks.", h: "Doing what you are told, straight away.", d: "ie", t: "O-BE-DI-ENT. The i comes before the e, and it finishes ENT, not ANT." },
  { w: "retriever", l: 4, p: "ie / ei", s: "Barley is part retriever, so he brings back sticks, socks and one whole shoe.", h: "A friendly dog famous for fetching things back to you.", d: "ie", t: "He TRIEs to fetch. TRIE hides in the middle, so it is i before e: re-TRIE-ver." },
  { w: "ridiculous", l: 4, p: "unstressed vowels", s: "Clifford squeezed into a tiny raincoat and looked completely ridiculous.", h: "So silly it makes everyone laugh out loud.", d: "icul", t: "Chop it up: RID-I-CUL-OUS. The middle is i then CUL, and it ends OUS like famous." },
  { w: "rottweiler", l: 4, p: "double letters", s: "Norman the cat stared down a rottweiler and won without moving.", h: "A big strong guard dog with a black and tan coat.", d: "ttwei", t: "Two t's, then w, then e before i. Think of his WEIght: rot-t-WEI-ler." },
  { w: "unbelievable", l: 4, p: "ie / ei", s: "It is unbelievable how fast Garfield moves when lasagne appears.", h: "So amazing you can hardly trust your own eyes.", d: "lieva", t: "Take BELIEVE, drop its last e, then add ABLE. Never beLIEve a LIE, so the middle stays l-i-e-v-a." },
  { w: "veterinarian", l: 4, p: "unstressed vowels", s: "The veterinarian said Mable is perfectly healthy, just perfectly round.", h: "An animal doctor who checks paws, teeth and tails.", d: "erina", t: "Say every sleepy vowel out loud: VET-ER-IN-AR-IAN. Five chunks, and the vet is right at the front." },
];

export const MILLIE_PRAISE = [
  "Correct. Fine. Take the coins. I was saving those for tuna.",
  "Spelled perfectly. Hatchi is wagging so hard the floor moved.",
  "Right again. Even Kumo sat up, and Kumo never sits up.",
  "Flawless. I shall permit one royal head pat. One.",
  "Correct. Garfield would have got that wrong and blamed the lasagne.",
  "Nailed it. Norman is pretending he knew it too. He did not.",
  "Perfect. Barley did a spin. That is his entire review.",
  "Correct, and I had to pay you out with my own paw. Outrageous.",
  "Spot on. Rosie has awarded you her second favourite squeaky ball.",
  "Yes. Snoopy would have needed his typewriter for that one.",
  "Right. Fluffington says well done, then went straight back to sleep on the good chair.",
];

// Streak 3+: Donut gets louder
export const MILLIE_PRAISE_HOT = [
  "Three in a row. My royal whiskers are twitching.",
  "Four. The dogs have formed a small parade. I did not approve it.",
  "Five straight. Kumo, Norman and Fluffington are all awake at once. That has never happened.",
  "Six. My treat jar is getting nervous, and so am I.",
  "Seven. Scooby fainted and Barley caught him. Unbelievable.",
  "Unstoppable. I am a queen and even I am clapping. With paws. Quietly.",
];

export const MILLIE_ROASTS = [
  "Not quite. Hatchi ate one of those letters. He eats everything.",
  "Nope, but so close. Even I had to check twice, and I am royalty.",
  "Missed it. Kumo would like it known that he was napping and saw nothing.",
  "Wrong, so I keep my coins. Honestly this is my favourite outcome.",
  "Ooh. One letter wandered off. Go and fetch it.",
  "Not this time. Odie spells like that too and he is very happy.",
  "Nearly. That word is slippery, like Norman in a cardboard box.",
  "Missed. Back in the pile it goes to try you again later. Very rude of it.",
  "Nope. Mable made that exact same face when she met a cucumber.",
  "Wrong letters, right spirit. The royal desk allows one more look.",
];

export const MILLIE_GENERIC_TRICK = "No royal trick for this one. Stare hard at the letters and take a brain photo. Cats do this all day. We call it staring.";

export const MILLIE_BOSS_TAUNTS = [
  "Royal Five. Five hard words, no bet needed, and $5 of my own money if you win. I regret this already.",
  "Feel brave? Five monster words, free to try. Beat them and I hand over $5 with a very sad little face.",
  "The Royal Five are waiting. Costs you nothing. Could cost me five whole dollars.",
  "Five words so tricky that Barley hid under the table. Win and the $5 is yours.",
  "Step up to the Royal Five. Free entry, $5 prize, one extremely worried queen.",
];

export const MILLIE_RANKS: Rank[] = [
  { wins: 0, title: "Wobbly Puppy" },
  { wins: 3, title: "Sock Thief" },
  { wins: 7, title: "Zoomie Rookie" },
  { wins: 12, title: "Chief Tail Wagger" },
  { wins: 18, title: "Cardboard Box Captain" },
  { wins: 25, title: "Windowsill Commander" },
  { wins: 35, title: "Sunbeam Champion" },
  { wins: 50, title: "Duchess of Doodles" },
  { wins: 75, title: "Knight of the Royal Cushion" },
  { wins: 100, title: "Legend of the Treat Jar" },
];

export const MILLIE_DOODLES: Doodle[] = [
  { id: "squeaky-ball", icon: "🎾", name: "Squeaky Ball", cap: "Squeaks once. Barley squeaks back for an hour.", rare: false },
  { id: "catnip-mouse", icon: "🐭", name: "Catnip Mouse", cap: "A fake mouse. Norman still checks it for a pulse.", rare: false },
  { id: "golden-collar", icon: "🥇", name: "Golden Collar", cap: "Shiny, heavy and completely unnecessary. Perfect.", rare: false },
  { id: "tiny-crown", icon: "👑", name: "Donut's Spare Crown", cap: "She owns three. She insists she needs four.", rare: true },
  { id: "sardine-tin", icon: "🐟", name: "Posh Sardine Tin", cap: "Opened once. The whole street came running.", rare: false },
  { id: "chewed-sock", icon: "🧦", name: "Chewed Sock", cap: "Hatchi's finest work. Do not put it on your foot.", rare: false },
  { id: "cardboard-box", icon: "📦", name: "Best Box Ever", cap: "Cost nothing. Beats every cat bed in the house.", rare: false },
  { id: "bone-biscuit", icon: "🦴", name: "Bone Biscuit", cap: "Rosie buried it. Rosie forgot where. Rosie is upset.", rare: false },
  { id: "ball-of-wool", icon: "🧶", name: "Ball of Wool", cap: "Twelve seconds of fun. Two hours of untangling.", rare: false },
  { id: "laser-dot", icon: "🔴", name: "Laser Dot", cap: "Never caught. Never will be. Kumo strongly disagrees.", rare: false },
  { id: "sunbeam-patch", icon: "☀️", name: "Warm Sunbeam", cap: "The best spot in the house, and it keeps moving. Rude.", rare: false },
  { id: "diamond-food-bowl", icon: "💎", name: "Diamond Food Bowl", cap: "For a queen who eats the exact same biscuits as everyone else.", rare: true },
];
