// Millie's word bank and persona: Princess Donut, a doodle cat who is
// certain she is royalty, runs the betting desk for a 9-year-old who loves
// cats and dogs. Words are cat, dog and pet themed, including the family's
// own animals and famous cartoon pets.
import type { Entry, Rank, Doodle } from "./engine";

export const MILLIE_BANK: Entry[] = [
  // Level 1
  { w: "another", l: 1, p: "unstressed vowels", s: "Hatchi had already eaten one biscuit, yet he tilted his head hopefully for another.", h: "one more of the same kind", d: "er", t: "It is an + other squashed together, and other keeps its er ending. No extra letters needed." },
  { w: "basket", l: 1, p: "unstressed vowels", s: "Kumo sleeps in the dog basket, and Hatchi is too polite to say anything.", h: "A woven box for a pet to sleep in.", d: "ket", t: "It sounds like bask-it, but the lazy vowel is really an e. Say bas-KET loudly to hear it." },
  { w: "because", l: 1, p: "letter patterns", s: "Norman refused to move off the warm laptop because it was the best bed in the house.", h: "the word you use when you are giving a reason", d: "au", t: "Say it in two chunks: be + cause. The reason word cause keeps its au right inside." },
  { w: "Bluey", l: 1, p: "cartoon pets", s: "Bluey turns one cardboard box into an entire adventure.", h: "The cartoon Australian heeler pup who makes up a game for everything.", d: "ey", t: "Take the colour of the sky, then pop a y on the end. Blue plus y, and the e stays in the middle." },
  { w: "caught", l: 1, p: "letter patterns", s: "Barley leapt after the frisbee, caught it in his teeth, and then refused to hand it back.", h: "grabbed something out of the air before it landed", d: "augh", t: "It rhymes with taught, and both hide augh. The g and h are the silent pair: c-augh-t." },
  { w: "children", l: 1, p: "plurals", s: "At the school fair, Barley followed a line of children for ten minutes because one of them had an ice cream.", h: "More than one young person.", d: "ren", t: "Child does not add s. It adds ren instead, so one child becomes children. To show what they own, add an apostrophe and s: children's shoes." },
  { w: "coming", l: 1, p: "suffixes", s: "Nobody has said the word walk, but Barley is already coming down the hallway with the lead in his mouth.", h: "on the way here, getting closer", d: "oming", t: "Take come, drop the e, then add ing. One m only, so it ends up c-oming." },
  { w: "crawl", l: 1, p: "letter patterns", s: "Hatchi can crawl right under the bed the second the vacuum cleaner wakes up.", h: "Going along on hands and knees, like a baby.", d: "aw", t: "The or sound here is spelled aw, just like claw, paw and yawn. There is no u and no r hiding in it." },
  { w: "cuddle", l: 1, p: "double letters", s: "Rosie wanted a cuddle at six in the morning. Dad said no. Rosie won.", h: "A warm hug in your arms.", d: "dd", t: "It takes two arms, so it takes two d's. Finish with a quiet e that says nothing." },
  { w: "dance", l: 1, p: "soft c and g", s: "Princess Donut refuses to dance, but her tail flicks along with the music whenever nobody is looking.", h: "To move your body in time with music.", d: "ce", t: "Drop the over-generalised sentence. Replace with: \"When c comes before e it says s, so this word ends in ce like ice, fence and prince. After an n sound, the soft s ending is nearly always ce: dance, chance, prince, fence.\"" },
  { w: "digging", l: 1, p: "ing doubling", s: "Rosie is digging a tunnel to the neighbour's garden. She is halfway there.", h: "Making a hole in the ground.", d: "gg", t: "DIG plus G plus ING. Short word, one vowel, so double the last letter before ING." },
  { w: "family", l: 1, p: "unstressed vowels", s: "The whole family agreed that Princess Donut runs the house, and Princess Donut agreed too.", h: "the group you live with and belong to", d: "mil", t: "Tap out three beats: fam-i-ly. That sleepy middle i is easy to drop, so keep it safe between the m and the l." },
  { w: "foxes", l: 1, p: "plurals", s: "Two foxes sat on the fence and watched Hatchi bark bravely at a bin.", h: "More than one bushy-tailed wild animal.", d: "es", t: "Words ending in X need ES so you can hear the plural: box-es, fox-es, six-es." },
  { w: "gentle", l: 1, p: "soft c and g", s: "Be gentle with Mr Fluffington. He is mostly fluff and opinions.", h: "Soft and careful, not rough.", d: "ge", t: "G before E says J: GEntle. Then the quiet LE on the end, said soft like a whisper." },
  { w: "ginger", l: 1, p: "soft c and g", s: "A ginger cat sat in Norman's spot. Norman has not forgiven anyone since.", h: "Orange-red in colour, like a spicy root.", d: "gi", t: "G before i says j: GInger. The second g goes soft too, because an e comes straight after it." },
  { w: "half", l: 1, p: "silent letters", s: "One whole lasagne is never enough for Garfield, and half a lasagne is basically an insult.", h: "One of two equal parts.", d: "l", t: "There is a silent l in here, just like calf, calm and walk. You cannot hear it, so you have to remember to put it in before the f." },
  { w: "know", l: 1, p: "homophones", s: "Somehow Kumo always seems to know when the tuna tin is opening, even from three rooms away.", h: "To have facts in your head already. Not the opposite of yes.", d: "kn", t: "This one keeps the silent k of knee, knock and knife. The plain word no has no k at all, so the k tells you it is the one about facts." },
  { w: "Kumo", l: 1, p: "pet names", s: "Kumo appears out of nowhere, stares at nothing, then vanishes again.", h: "The mysterious cat with a Japanese name that means cloud.", d: "Ku", t: "It sounds like coo, but it starts with K and u. Mystery cats begin with K: Ku plus mo." },
  { w: "people", l: 1, p: "hidden letters", s: "Kumo stares at a blank wall until people start staring at the blank wall too.", h: "more than one human being", d: "eo", t: "Here eo says just ee. Picture the o hiding quietly between the e and the second p: p-eo-p-l-e." },
  { w: "remember", l: 1, p: "unstressed vowels", s: "Norman can remember exactly which cushion is his, even in the dark.", h: "to bring something back into your mind", d: "ember", t: "The end is ember, like a glowing ember in a fire: rem + ember." },
  { w: "right", l: 1, p: "homophones", s: "Which paw is the right one? Barley just offers whichever paw is closest and hopes that it counts.", h: "The opposite of left, or correct. Not the one you do with a pen.", d: "igh", t: "Either move \"right\" to \"letter patterns\" (igh) and leave write in silent letters, or keep both in homophones and add the contrast: \"igh spells the long i sound like night and bright. This is the right that means correct or not-left; the write you do with a pen starts with wr.\"" },
  { w: "scratch", l: 1, p: "letter patterns", s: "Do not scratch the couch, Kumo. Kumo scratched the couch.", h: "To drag claws across something.", d: "tch", t: "Short vowel words end in TCH: caTCH, maTCH, scraTCH. The T sneaks in before the CH." },
  { w: "should", l: 1, p: "silent letters", s: "Mable thinks she should be allowed on the sofa, the bed and the dinner table.", h: "the word you use for something that is a good idea to do, or the right thing to do", d: "ould", t: "could, would and should all share the ending ould. The l says nothing, but you still have to write it." },
  { w: "stopped", l: 1, p: "ing doubling", s: "Princess Donut stopped washing her paw so she could glare at the dog walking past.", h: "no longer moving or carrying on", d: "pp", t: "One short vowel and one final p means you double the p before ed, so two p's march in front of the ed." },
  { w: "their", l: 1, p: "homophones", s: "The dogs raced outside and found their tennis ball parked neatly in Norman's food bowl.", h: "Belonging to them, like their dog. Not the one meaning in that place.", d: "eir", t: "Keep it as a letters-only hook with a correct definition: \"Look for the letters t + heir. An heir is the person who inherits a family's things, which makes it easy to remember that this their is the belonging-to one. There is for places, and they're is short for they are.\"" },
  { w: "thought", l: 1, p: "ough words", s: "Mr Fluffington thought the doorbell was announcing guests for him personally.", h: "The past of think, an idea you had. Not the one meaning to have given a lesson.", d: "ough", t: "Break it as th + ought, and ought is a whole word on its own. Same ough family as bought, brought and fought." },
  { w: "through", l: 1, p: "ough words", s: "Rosie squeezed through the cat flap and got a very rude look from Princess Donut.", h: "In one side and out the other, like going through a gate. Not the one meaning very careful, and not the past of throw.", d: "ough", t: "It starts like thr in throw and finishes with ough: thr + ough. The other one, threw, as in I threw the ball, has no gh in it at all." },
  { w: "water", l: 1, p: "unstressed vowels", s: "Mable barks at her own reflection in the water bowl every single morning.", h: "the clear drink that pours out of a tap", d: "er", t: "The ending sounds lazy, like uh, but it is spelled er, the same er as in later and after." },
  { w: "write", l: 1, p: "silent letters", s: "Rosie would write a thank you note for every biscuit if only she could hold a pen.", h: "To make letters and words with a pen. Not the opposite of left.", d: "wr", t: "The r sound at the start is spelled wr, like wrist, wrap and wrong. You never hear the w, but you always write it first." },
  // Level 2
  { w: "adopted", l: 2, p: "letter patterns", s: "We adopted Rosie. Then Rosie adopted the entire sofa.", h: "Took an animal home to be part of your family for good.", d: "pted", t: "Just add ED to the end. Do not double the t: adopTED, one t only." },
  { w: "autumn", l: 2, p: "silent letters", s: "Every autumn Barley dives into the leaf pile and comes out wearing half the garden on his back.", h: "The season of falling leaves that comes after summer.", d: "mn", t: "There is a silent n hiding on the end, in the letters mn. Say 'autum-N' inside your head, like the n you cannot hear in column and hymn." },
  { w: "Barley", l: 2, p: "pet names", s: "Barley chased his own tail and fell straight into the paddling pool.", h: "The goofiest dog in the house, named after a crop that farmers grow.", d: "ley", t: "Bar plus ley. Only ONE l, and the e comes before the y, just like Bluey." },
  { w: "believe", l: 2, p: "ie / ei", s: "Kumo can open a cupboard so quietly that visitors refuse to believe he did it.", h: "To accept that something is true.", d: "lie", t: "Never trust a lie, and a lie sits right in the middle of this word: be-lie-ve. Spotting it keeps the i in front of the e." },
  { w: "carried", l: 2, p: "suffixes", s: "Norman carried one lonely sock down the hallway and dropped it right where everyone walks.", h: "Took something from one place to another in your arms or mouth.", d: "ied", t: "Carry ends in a consonant plus y, so change the y to i before adding -ed: carr + i + ed. Both r's stay put." },
  { w: "collar", l: 2, p: "double letters", s: "Rosie's collar has a bell, so every squirrel gets a fair warning.", h: "A band that goes round a pet's neck.", d: "ll", t: "Two l's in the middle, and it ends in ar, not er. Like a star round the neck." },
  { w: "couldn't", l: 2, p: "apostrophes", s: "Garfield couldn't be bothered to fetch the remote, so he asked Odie to do it.", h: "The short way of saying you were not able to do something.", d: "dn't", t: "It is could not pushed together. The apostrophe sits exactly where the o of not was taken out: could + n + ' + t." },
  { w: "decision", l: 2, p: "tion words", s: "Mr Fluffington announced his big decision, and now the top shelf of the bookcase is his throne.", h: "A choice you make after thinking it over.", d: "sion", t: "Cut \"or d\". Use: \"The base word is decide, which ends in de. Base words ending in -de swap the de for -sion: decide becomes decision, divide becomes division, explode becomes explosion.\"" },
  { w: "different", l: 2, p: "unstressed vowels", s: "Norman has a different grumpy face for every meal of the day.", h: "not the same as another thing", d: "fer", t: "Anchor it to the base word: \"It is differ + ent, and differ keeps its er. Say DIFF-er-ent in three beats when you spell it, even though we squash it to two when we talk fast.\"" },
  { w: "dogs'", l: 2, p: "apostrophes", s: "Every one of the dogs' tails started wagging when the biscuit tin lid squeaked open.", h: "Belonging to more than one barking pet.", d: "s'", t: "More than one already ends in s, so the apostrophe goes after the s. Write the plural first, then add the apostrophe: d-o-g-s and then '." },
  { w: "Donut", l: 2, p: "pet names", s: "Princess Donut yawns on her throne of warm, clean laundry.", h: "The royal cat, named after a sweet ring-shaped treat.", d: "nu", t: "Do plus nut, like a nut you can eat. One n is plenty, because there is only one princess." },
  { w: "eight", l: 2, p: "letter patterns", s: "Mable counted eight tennis balls under the sofa and carried every single one of them to her bed.", h: "The number after seven. Not the past of eat.", d: "eigh", t: "eigh spells the long a sound, the same as weight and sleigh. Say the letters as a chant: e-i-g-h-t, with the g and h staying silent." },
  { w: "field", l: 2, p: "ie / ei", s: "Bluey and Bingo raced twice around the field, and both of them insisted they had won.", h: "A wide open space of grass where animals graze.", d: "ie", t: "Attach the condition and name an exception: \"The long e sound here is spelled ie. Use the rhyme with its rule attached: i before e, except after c, when the sound is ee. That is why field, piece and thief take ie, but eight and weight are a different sound and use ei.\"" },
  { w: "friendly", l: 2, p: "ie / ei", s: "Hatchi is so friendly that even the postman gets a cuddle.", h: "Kind and warm to everyone you meet.", d: "ie", t: "There is an END in it with an i before: fri-END-ly." },
  { w: "happiness", l: 2, p: "suffixes", s: "For Scooby, happiness is a sandwich roughly the size of a pillow.", h: "The warm feeling you get when everything is going well.", d: "iness", t: "Happy ends in a consonant plus y, so change the y to i before adding -ness: happ + i + ness. Keep both p's." },
  { w: "Hatchi", l: 2, p: "pet names", s: "Hatchi waits by the front door for hours, just in case you come home early.", h: "The most loyal dog in the family, always on guard by the door.", d: "tch", t: "There is a caTCH in the middle: t, c, h all in a row, like the hatch on a boat. Say hat-chee and hear the hidden t." },
  { w: "hoping", l: 2, p: "suffixes", s: "Bingo sat under the table all dinner, hoping a sausage would fall by accident.", h: "Wishing that something good will happen.", d: "oping", t: "Hope ends in e, so drop the e before -ing and keep just one p: hop + ing. Two p's would give you hopping, which means jumping." },
  { w: "Mable", l: 2, p: "pet names", s: "Mable howls like the world is ending, just because her bowl is nearly empty.", h: "The most dramatic dog alive, who treats every small thing as an emergency.", d: "le", t: "She ends with a sleepy le, not el. Ma plus b plus le, like table and cradle." },
  { w: "misbehave", l: 2, p: "prefixes", s: "Mable would never misbehave in front of visitors, but the muddy paw prints on the clean sofa say otherwise.", h: "To act badly on purpose and break the rules.", d: "mis", t: "The prefix mis- means badly or wrongly, and it has just one s. Stick it straight on the front: mis + behave, with behave keeping every letter." },
  { w: "naughty", l: 2, p: "letter patterns", s: "Who was naughty? All four dogs looked straight at Mable.", h: "Badly behaved and cheeky.", d: "augh", t: "N-AUGH-TY. The AUGH says OR, the same as cAUGHt and tAUGHt. Cheeky dogs get caught." },
  { w: "Norman", l: 2, p: "pet names", s: "Norman is shaped like a loaf of bread and grumpy like thunder.", h: "The grumpy cat with a very ordinary human name.", d: "man", t: "He sounds like Nor-mun, but he ends in man, like a person. Nor plus man, because he is a tiny angry gentleman." },
  { w: "piece", l: 2, p: "homophones", s: "Mr Fluffington accepted one piece of cheese and then licked the wrapper clean just in case.", h: "A bit cut or broken off something bigger. Not the calm quiet one.", d: "pie", t: "A pie comes first, then add ce: pie + ce. The quiet sort of peace has pea in it instead, so pie means a part of something." },
  { w: "pounce", l: 2, p: "soft c and g", s: "Donut waits behind the door, ready to pounce on a stray sock.", h: "To jump suddenly onto something.", d: "ce", t: "It ends in CE, not se. The C does the hissing: poun-CE. Same as danCE and prinCE." },
  { w: "prepare", l: 2, p: "prefixes", s: "Rosie likes to prepare for a walk by sitting on her lead so nobody can pick it up.", h: "To get everything ready ahead of time.", d: "pre", t: "The prefix pre- means before, so getting ready before is pre + pare. It is spelled p-r-e, never per." },
  { w: "puppies", l: 2, p: "plurals", s: "Six puppies, one basket, zero peace.", h: "More than one baby dog.", d: "ies", t: "One puppy, lots of puppies. The Y gets shy, hides, and turns into IES." },
  { w: "question", l: 2, p: "tion words", s: "Princess Donut has the same question at every meal: why is the chicken not in the bowl yet?", h: "Something you ask when you want to know an answer.", d: "quest", t: "The whole word quest is hiding inside it. A quest for an answer, then add -ion. And remember q always drags a u along behind it." },
  { w: "quiet", l: 2, p: "homophones", s: "Kumo is so quiet that Norman never hears him arrive, which is exactly the plan.", h: "Making almost no sound. Not the one that means very or fairly.", d: "iet", t: "Two beats, KWY-et, so the e comes before the t. The one-beat word quite ends in e instead." },
  { w: "rescue", l: 2, p: "letter patterns", s: "We had to rescue Mable from the laundry basket. Again.", h: "To save someone from danger.", d: "cue", t: "RES plus CUE. It ends like a snooker CUE, never cew. Every rescue needs a CUE." },
  { w: "Rosie", l: 2, p: "pet names", s: "Rosie says hello by licking the postman's shoes, every single day.", h: "The sweetest dog in the house, named after a pink garden flower.", d: "ie", t: "She ends with i before e, like a little smile. Ros plus i-e, never e-y." },
  { w: "Scooby", l: 2, p: "cartoon pets", s: "Scooby will face any ghost, as long as there is a giant sandwich in it.", h: "The big brown Great Dane who is scared of spooks but loves snacks.", d: "oo", t: "Double o, like two big scared eyes staring at a ghost. His famous shout ends in Doo, and Doo has oo, so he does too." },
  { w: "Snoopy", l: 2, p: "cartoon pets", s: "Snoopy sleeps on the roof of his kennel and never once falls off.", h: "The white beagle with black ears who dreams of being a flying ace.", d: "oo", t: "He snoozes on a roof, and roof has double o. So does his name: Sn, oo, py." },
  { w: "snuggle", l: 2, p: "double letters", s: "Rosie will snuggle anyone who sits still for three whole seconds.", h: "To curl up close for warmth and cuddles.", d: "gg", t: "Two G's, then the quiet LE: snu-GG-le. Same shape as wriggle and giggle." },
  { w: "station", l: 2, p: "tion words", s: "Hatchi waited at the train station like a furry statue until Dad finally stepped off the train.", h: "A place where trains stop to let people on and off.", d: "tion", t: "The /shun/ sound at the end is spelled t-i-o-n. Think of stat, as in a statue standing still, then add -ion: stat + ion." },
  { w: "submarine", l: 2, p: "prefixes", s: "Kumo spent the morning inside a cardboard submarine, then surfaced to demand his dinner.", h: "A boat that travels along under the water.", d: "sub", t: "The prefix sub- means under, and marine means to do with the sea. An under-the-sea boat is sub + marine, and nothing changes when you join them." },
  { w: "tabby", l: 2, p: "double letters", s: "Kumo is a tabby, and he is certain that makes him a tiger.", h: "A cat with a stripy coat and often an M on its forehead.", d: "bby", t: "A short A needs two B's before the Y: ta-BB-y. Like chubby and hobby." },
  { w: "tongue", l: 2, p: "silent letters", s: "Hatchi's tongue hangs out even when he is fast asleep.", h: "The pink thing in your mouth that tastes your food.", d: "gue", t: "It ends in GUE, like leaGUE. The U and E say nothing. Hatchi's never says nothing." },
  { w: "wagging", l: 2, p: "ing doubling", s: "Barley's tail was wagging so hard it cleared the whole coffee table.", h: "Swishing a tail back and forth with joy.", d: "gg", t: "WAG plus G plus ING. Double the G, or you get waging, which no tail has ever done." },
  // Level 3
  { w: "although", l: 3, p: "ough words", s: "Mable refused to go outside although the rain had stopped an hour ago.", h: "a joining word that means even though", d: "ough", t: "Here ough says oh, the same as in though and dough. Build it as al + though, with only one l." },
  { w: "beautiful", l: 3, p: "letter patterns", s: "Kumo sat in the sunbeam looking beautiful and refusing to move for anyone.", h: "Really lovely to look at.", d: "eau", t: "Big Ears Are Useful: B-E-A-U. That is the tricky start." },
  { w: "behaviour", l: 3, p: "our words", s: "Princess Donut earned a gold star for good behaviour at the vet, then hissed at the receptionist on the way out.", h: "The way a person or animal acts.", d: "our", t: "Limit the claim to the word family: \"New Zealand keeps the u in this family, just like colour, neighbour and flavour. Write -our, not the American -or. (Words like doctor and visitor are a different family and keep -or.)\"" },
  { w: "biscuit", l: 3, p: "silent letters", s: "Hatchi can hear a biscuit tin open from the other end of town.", h: "A crunchy little treat, great for dogs and for dunking.", d: "cui", t: "After the c sneaks in a silent u: bis-C-U-it. The u says nothing at all." },
  { w: "brilliant", l: 3, p: "double letters", s: "Mable had a brilliant plan. The plan was to eat the plan.", h: "Super clever, or shining really bright.", d: "ll", t: "Double l in the middle, like two bright bulbs: bri-LL-iant." },
  { w: "chocolate", l: 3, p: "unstressed vowels", s: "Mr Fluffington guarded the chocolate cake all afternoon like a museum security cat.", h: "a sweet brown treat made from cocoa beans", d: "cola", t: "There is a cola hiding in the middle: cho-COLA-te. Say the three beats CHOC-O-LATE and you will hear that lazy o you nearly miss." },
  { w: "Clifford", l: 3, p: "cartoon pets", s: "Clifford wagged his tail once and knocked over a bus.", h: "The giant red dog from the storybooks who is taller than a house.", d: "fford", t: "A cliff plus a Ford car. Cliff brings double f, then ord like a Ford, never urd." },
  { w: "climbed", l: 3, p: "silent letters", s: "Mable climbed onto the warm clean washing and announced that it belonged to her now.", h: "went up something using hands and feet", d: "mb", t: "The b is silent after m, like lamb and comb. Then just add plain -ed, with nothing doubled: climb + ed." },
  { w: "cushion", l: 3, p: "letter patterns", s: "Norman claimed the best cushion in the house and will not be moved.", h: "A soft pad you sit on.", d: "shio", t: "cu-SHI-ON. It is SHI then ON, not TION. Hear the SH, then land on the ION." },
  { w: "delicious", l: 3, p: "soft c and g", s: "Hatchi believes anything that hits the floor is instantly delicious.", h: "Tasting so good you want the whole bowl.", d: "cious", t: "This c hisses like SH. It sounds like lish, but you write CIOUS." },
  { w: "disappeared", l: 3, p: "double letters", s: "The last biscuit disappeared, and Hatchi looks completely innocent.", h: "Vanished and nowhere to be found.", d: "sapp", t: "One s, then two p's: DIS plus APPEAR plus ED. The APPEAR half keeps its double p and its EAR." },
  { w: "enormous", l: 3, p: "letter patterns", s: "An enormous cat called Norman is sitting on my homework again.", h: "Really, really huge.", d: "ous", t: "It ends OUS, like a mouse with no e. Big words love an OUS ending." },
  { w: "exercise", l: 3, p: "letter patterns", s: "Barley's idea of exercise is one lap of the garden, then a long nap.", h: "Moving your body to keep it fit and strong.", d: "erc", t: "An x, then er, then a c: e-X-e-R-C-ise. No s hiding in the middle." },
  { w: "favourite", l: 3, p: "our words", s: "Barley's favourite game is stealing one sock and running for the door.", h: "The one you like best of all.", d: "our", t: "It is OUR pick, so keep the u in: fav-OUR-ite." },
  { w: "Fluffington", l: 3, p: "pet names", s: "Mr Fluffington sat on the keyboard and typed his own name: Fluffington.", h: "The very posh second name of the family's puffiest cat.", d: "ff", t: "Break the posh name into three bits: FLUFF with two f's, then ing, then ton like a little town." },
  { w: "Garfield", l: 3, p: "cartoon pets", s: "Garfield ate the whole lasagne, then asked what was for dinner.", h: "The fat orange comic cat who hates Mondays and loves lasagne.", d: "field", t: "Gar plus field. A field of lasagne, and every field has i before e." },
  { w: "gorgeous", l: 3, p: "soft c and g", s: "Mable rolled in mud and still thought she looked absolutely gorgeous.", h: "So lovely that people stop and stare.", d: "geous", t: "Keep the e after the g so the g stays soft: G-E-O-U-S." },
  { w: "greyhound", l: 3, p: "letter patterns", s: "A greyhound zoomed past Kumo so fast that his whiskers blew backwards.", h: "A slim super fast dog built like a rocket on legs.", d: "ey", t: "Here it is grEY with an e, then hound. Grey dogs, never gray ones." },
  { w: "labrador", l: 3, p: "unstressed vowels", s: "Hatchi told the labrador that the couch was already taken, thank you.", h: "A big friendly dog, often yellow, black or chocolate.", d: "rador", t: "Lab plus RADOR. The sleepy vowel after the b is an a, not an o: lab-RA-dor." },
  { w: "licence", l: 3, p: "homophones", s: "Rewrite around a licence a NZ child recognises, e.g. \"Dad had to show his driver licence at the vet, and Barley tried to eat it.\" If you keep a dog reference, use \"dog registration form\" and pick a different word.", h: "The official paper that lets you do something, spelled the noun way.", d: "ce", t: "The naming word ends in -ce, like a piece of paper you can hold. The doing word, to license, ends in -se." },
  { w: "lightning", l: 3, p: "letter patterns", s: "Scooby would run from lightning, but Rosie just wags her tail at the window.", h: "a bright flash in the sky during a storm", d: "ightn", t: "igh makes the long i sound, then the t and n snap together with no e: light + ning. Slip an e in and you get lightening, which means going paler." },
  { w: "medicine", l: 3, p: "soft c and g", s: "We hide Rosie's medicine in a lump of cheese. She eats the cheese and leaves the medicine.", h: "Something you take to help you get well again.", d: "ci", t: "Medi plus CINE. The c says s because an i comes next." },
  { w: "mischief", l: 3, p: "ie / ei", s: "Donut caused so much mischief that the tinsel is now in the fish tank.", h: "Playful naughty trouble that makes grown-ups sigh.", d: "ie", t: "The chief of the gang has IE, and so does this word. I before E." },
  { w: "muscle", l: 3, p: "silent letters", s: "Norman flexed one muscle, got tired, and went straight back to sleep.", h: "The strong stretchy part inside you that makes your body move.", d: "sc", t: "There is a silent c. You can hear it wake up in muscular: mus-Cular." },
  { w: "neighbour", l: 3, p: "ie / ei", s: "Our neighbour's cat pops in for lunch with Norman every single day.", h: "The person who lives right next door to you.", d: "eigh", t: "Neigh like a horse, then bour. E comes before i: n-E-I-G-H." },
  { w: "pause", l: 3, p: "homophones", s: "Norman likes to pause exactly halfway through the doorway to enjoy the traffic jam.", h: "A short stop before carrying on. Not an animal's feet.", d: "au", t: "Swap in true /ɔː/ examples: \"au gives the or sound, like sauce, haunted and applaud. A cat's paws use aw, but stopping uses au.\"" },
  { w: "practise", l: 3, p: "homophones", s: "Princess Donut makes Barley practise bowing to her every single morning.", h: "To do something over and over to get better, the doing-word spelling.", d: "se", t: "The doing word ends in -se, just like use. The naming word is practice with a c, like ice." },
  { w: "recognise", l: 3, p: "hidden letters", s: "Kumo can recognise a tuna tin opening from three rooms away.", h: "To know something the moment you see or hear it again.", d: "gn", t: "There is a hidden g. Say re-COG-nise to hear it, then finish with ISE." },
  { w: "scissors", l: 3, p: "silent letters", s: "The scissors went missing for a week and turned up in Barley's blanket pile.", h: "a tool with two blades for cutting paper", d: "sc", t: "Two blades, so two letters that make one hissing s sound at the start: sc, just like science and scene." },
  { w: "separate", l: 3, p: "unstressed vowels", s: "We had to separate Norman and Kumo before the great sofa war began.", h: "To move things apart so they are not together.", d: "para", t: "There is A RAT in sep-A-RAT-e. Say the rat out loud and the middle a can never turn into an e." },
  { w: "shelves", l: 3, p: "plurals", s: "There are three shelves in the bedroom, and Princess Donut sleeps on the highest one, of course.", h: "flat boards on a wall for holding books", d: "ves", t: "Keep only -f examples so the rule holds: \"One shelf, two of them: swap the f for a v and add es, just like half to halves and wolf to wolves.\" If knife is wanted, state the rule as \"change the f or fe ending to ves\"." },
  { w: "terrier", l: 3, p: "double letters", s: "Rosie is a terrier, and every terrier is certain it owns the whole street.", h: "A small bouncy kind of dog that loves digging holes.", d: "rr", t: "Two r's in the middle, like two ears on one very busy dog: te-RR-ier." },
  { w: "weight", l: 3, p: "homophones", s: "Mr Fluffington sat on the bathroom scales to check the weight of one very important cat.", h: "How heavy something is. Not the one that means to stay until later.", d: "eigh", t: "eigh says long a, like eight and sleigh. You weigh a cat to find its weight, but you wait for the bus with ai." },
  { w: "wriggle", l: 3, p: "silent letters", s: "Donut can wriggle out of any cuddle in under two seconds.", h: "To twist and squirm about like a wiggly worm in the grass.", d: "wr", t: "Silent w at the start, like in write, wrong and wrap. Then two g's in the middle: wri-GG-le." },
  // Level 4
  { w: "adorable", l: 4, p: "letter patterns", s: "Mable snoring upside down is completely adorable, and completely loud.", h: "So cute you want to squeeze it.", d: "able", t: "Take ADORE, throw away the e, then add ABLE. If you adore her, she is ABLE to be adored." },
  { w: "affectionate", l: 4, p: "double letters", s: "Rosie is so affectionate she licks your face before you are even awake.", h: "Full of cuddles and love for someone.", d: "ffection", t: "Double f, because one f is never enough love. Then it is AFFECTION plus ATE." },
  { w: "companion", l: 4, p: "unstressed vowels", s: "Snoopy picked one companion for life: Woodstock, a very small yellow bird.", h: "A friend who goes everywhere with you.", d: "panion", t: "COM plus PAN plus ION. A true pal shares your PAN of dinner, then you add ION like in onion." },
  { w: "curiosity", l: 4, p: "letter patterns", s: "Curiosity got Jiji stuck inside the laundry basket again.", h: "The itch to find out what something is.", d: "iosi", t: "Start with CURIOUS, drop the u, add ITY. The o stays behind: curi-OSI-ty." },
  { w: "definitely", l: 4, p: "unstressed vowels", s: "Rosie was definitely not on the sofa, said Rosie, from the warm dent in the sofa.", h: "For certain, without any doubt.", d: "finite", t: "Look for the word fin hiding in the middle, like a fish fin: de + fin + ite + ly. That mumbled vowel after the fin is an i, never an a." },
  { w: "embarrassed", l: 4, p: "double letters", s: "Nothing looks more embarrassed than Norman pretending he meant to slide off the windowsill.", h: "Feeling awkward and red-faced after something clumsy.", d: "rrass", t: "Really Red And Super Shy: two r's, then two s's, then a plain -ed on the end." },
  { w: "energetic", l: 4, p: "soft c and g", s: "Bluey is so energetic she wears out three tennis balls a day.", h: "Bursting with go and never sitting still.", d: "getic", t: "The g says j because an e follows it, and the ending is a hard c, not a k: GET-IC." },
  { w: "environment", l: 4, p: "suffixes", s: "Barley is convinced that the ideal environment for a nap is exactly where you were about to sit.", h: "The natural world, or the surroundings something lives in.", d: "onment", t: "It is environ plus the suffix -ment. Say en-vi-ron-ment slowly and sound that n before the -ment so it does not vanish." },
  { w: "February", l: 4, p: "hidden letters", s: "Every February, Mable stretches out in the hottest patch of sun and announces that summer was her idea.", h: "The second month of the year.", d: "bru", t: "Say it in slow chunks, Feb-roo-ary, and you can hear the hidden r sitting right after the b." },
  { w: "ferocious", l: 4, p: "soft c and g", s: "Princess Donut looks ferocious, then falls asleep inside a shoe.", h: "Fierce, growly and ready to pounce.", d: "cious", t: "That SH sound is really CIOUS, like delicious. C plus IOUS, never sh." },
  { w: "immediately", l: 4, p: "suffixes", s: "Hatchi appears immediately when the fridge door opens, as if he had been folded up behind it all along.", h: "Straight away, with no waiting at all.", d: "mm", t: "The prefix in- turns into im- before an m, so im plus mediate gives you the double m. Then keep the whole word and add -ly." },
  { w: "magnificent", l: 4, p: "soft c and g", s: "Mr Fluffington sat on the windowsill looking magnificent, then fell off.", h: "Really grand and impressive to look at.", d: "cent", t: "It ends with CENT, like a coin, not sent. A magnificent cat is worth every CENT." },
  { w: "mischievous", l: 4, p: "ie / ei", s: "Kumo has one mischievous trick: he switches off the wifi with a single paw and watches the humans panic.", h: "Playfully naughty in a cheeky way.", d: "ievous", t: "Start from mischief, change the f to v and add -ous. It has three beats, mis-chie-vous, so there is no extra i before the -ous." },
  { w: "mysterious", l: 4, p: "hidden letters", s: "Something mysterious ate the sausages, and Kumo looks very guilty.", h: "Strange and very hard to explain.", d: "yste", t: "The first vowel sound is a y, not an i. Write MYSTERY, then swap that last y for IOUS." },
  { w: "necessary", l: 4, p: "double letters", s: "Is a velvet cushion really a necessary part of lunch? Mr Fluffington says yes, and he will not discuss it.", h: "Needed, not just nice to have.", d: "cess", t: "One Collar and two Socks: one c, then double s. Say ne-cess-ary and listen for the hissing double s in the middle." },
  { w: "obedient", l: 4, p: "ie / ei", s: "Scooby is obedient right up until somebody mentions snacks.", h: "Doing what you are told, straight away.", d: "ie", t: "O-BE-DI-ENT. The i comes before the e, and it finishes ENT, not ANT." },
  { w: "retriever", l: 4, p: "ie / ei", s: "Barley is part retriever, so he brings back sticks, socks and one whole shoe.", h: "A friendly dog famous for fetching things back to you.", d: "ie", t: "He TRIEs to fetch. TRIE hides in the middle, so it is i before e: re-TRIE-ver." },
  { w: "ridiculous", l: 4, p: "unstressed vowels", s: "Clifford squeezed into a tiny raincoat and looked completely ridiculous.", h: "So silly it makes everyone laugh out loud.", d: "icul", t: "Chop it up: RID-I-CUL-OUS. The middle is i then CUL, and it ends OUS like famous." },
  { w: "unbelievable", l: 4, p: "ie / ei", s: "It is unbelievable how fast Garfield moves when lasagne appears.", h: "So amazing you can hardly trust your own eyes.", d: "lieva", t: "Take BELIEVE, drop its last e, then add ABLE. Never beLIEve a LIE, so the middle stays l-i-e-v-a." },
  { w: "veterinarian", l: 4, p: "unstressed vowels", s: "The veterinarian said Mable is perfectly healthy, just perfectly round.", h: "An animal doctor who checks paws, teeth and tails.", d: "erina", t: "Say every sleepy vowel out loud: VET-ER-IN-AR-IAN. Five chunks, and the vet is right at the front." },
];

export const MILLIE_PRAISE = [
  "Correct. Fine. Take the coins. I was saving those for tuna.",
  "Spelled perfectly. Hatchi is wagging so hard the floor moved.",
  "Right again. Even Kumo sat up, and Kumo never sits up.",
  "Flawless. I shall permit one royal head pat. One.",
  "Correct. Garfield would have got that wrong and blamed the lasagne.",
  "Nailed it. Norman is pretending he knew it too. He did not.",
  "Perfect. Barley did a spin. That is his entire review.",
  "Correct, and I had to pay you out with my own paw. Outrageous.",
  "Spot on. Rosie has awarded you her second favourite squeaky ball.",
  "Yes. Snoopy would have needed his typewriter for that one.",
  "Right. Fluffington says well done, then went straight back to sleep on the good chair.",
];

// Streak 3+: Donut gets louder
export const MILLIE_PRAISE_HOT = [
  "Three in a row. My royal whiskers are twitching.",
  "Four. The dogs have formed a small parade. I did not approve it.",
  "Five straight. Kumo, Norman and Fluffington are all awake at once. That has never happened.",
  "Six. My treat jar is getting nervous, and so am I.",
  "Seven. Scooby fainted and Barley caught him. Unbelievable.",
  "Unstoppable. I am a queen and even I am clapping. With paws. Quietly.",
];

export const MILLIE_ROASTS = [
  "Not quite. Hatchi ate one of those letters. He eats everything.",
  "Nope, but so close. Even I had to check twice, and I am royalty.",
  "Missed it. Kumo would like it known that he was napping and saw nothing.",
  "Wrong, so I keep my coins. Honestly this is my favourite outcome.",
  "Ooh. One letter wandered off. Go and fetch it.",
  "Not this time. Odie spells like that too and he is very happy.",
  "Nearly. That word is slippery, like Norman in a cardboard box.",
  "Missed. Back in the pile it goes to try you again later. Very rude of it.",
  "Nope. Mable made that exact same face when she met a cucumber.",
  "Wrong letters, right spirit. The royal desk allows one more look.",
];

export const MILLIE_GENERIC_TRICK = "No royal trick for this one. Stare hard at the letters and take a brain photo. Cats do this all day. We call it staring.";

export const MILLIE_BOSS_TAUNTS = [
  "I have set you a royal challenge. Costs you nothing, and it could cost me actual money. I regret it already.",
  "Feel brave? The rules are on the card, the prize is mine to lose, and I am not happy about it.",
  "A royal challenge is waiting. Free to try. Beat it and I hand the money over with a very sad little face.",
  "Words so tricky that Barley hid under the table. Read the rules and see if you dare.",
  "Step up. Free entry, real money, one extremely worried queen.",
  "The challenge stands. Norman says you will not manage it. Norman says that about everything.",
];

export const MILLIE_RANKS: Rank[] = [
  { wins: 0, title: "Wobbly Puppy" },
  { wins: 3, title: "Sock Thief" },
  { wins: 7, title: "Zoomie Rookie" },
  { wins: 12, title: "Chief Tail Wagger" },
  { wins: 18, title: "Cardboard Box Captain" },
  { wins: 25, title: "Windowsill Commander" },
  { wins: 35, title: "Sunbeam Champion" },
  { wins: 50, title: "Duchess of Doodles" },
  { wins: 75, title: "Knight of the Royal Cushion" },
  { wins: 100, title: "Legend of the Treat Jar" },
];

export const MILLIE_DOODLES: Doodle[] = [
  { id: "squeaky-ball", icon: "🎾", name: "Squeaky Ball", cap: "Squeaks once. Barley squeaks back for an hour.", rare: false },
  { id: "catnip-mouse", icon: "🐭", name: "Catnip Mouse", cap: "A fake mouse. Norman still checks it for a pulse.", rare: false },
  { id: "golden-collar", icon: "🥇", name: "Golden Collar", cap: "Shiny, heavy and completely unnecessary. Perfect.", rare: false },
  { id: "tiny-crown", icon: "👑", name: "Donut's Spare Crown", cap: "She owns three. She insists she needs four.", rare: true },
  { id: "sardine-tin", icon: "🐟", name: "Posh Sardine Tin", cap: "Opened once. The whole street came running.", rare: false },
  { id: "chewed-sock", icon: "🧦", name: "Chewed Sock", cap: "Hatchi's finest work. Do not put it on your foot.", rare: false },
  { id: "cardboard-box", icon: "📦", name: "Best Box Ever", cap: "Cost nothing. Beats every cat bed in the house.", rare: false },
  { id: "bone-biscuit", icon: "🦴", name: "Bone Biscuit", cap: "Rosie buried it. Rosie forgot where. Rosie is upset.", rare: false },
  { id: "ball-of-wool", icon: "🧶", name: "Ball of Wool", cap: "Twelve seconds of fun. Two hours of untangling.", rare: false },
  { id: "laser-dot", icon: "🔴", name: "Laser Dot", cap: "Never caught. Never will be. Kumo strongly disagrees.", rare: false },
  { id: "sunbeam-patch", icon: "☀️", name: "Warm Sunbeam", cap: "The best spot in the house, and it keeps moving. Rude.", rare: false },
  { id: "diamond-food-bowl", icon: "💎", name: "Diamond Food Bowl", cap: "For a queen who eats the exact same biscuits as everyone else.", rare: true },
];
