// Hunter's word bank and persona: Chip, the Big Nate flavoured house who takes
// your bet and trash-talks you through 127 words across 4 difficulty levels.
import type { Entry, Rank, Doodle } from "./engine";

export const HUNTER_BANK: Entry[] = [
  // Level 1
  { w: "because", l: 1, p: "letter patterns", s: "Nate can't sit near the art cupboard because of the glue incident. Nobody talks about the glue incident.", h: "For the reason that.", d: "ecau", t: "Big Elephants Can Always Understand Small Elephants. First letters spell BECAUSE. Nate would ride the elephant." },
  { w: "beautiful", l: 1, p: "letter patterns", s: "Nate framed his most beautiful doodle and awarded it first prize. The judge was Nate.", h: "Very lovely to look at.", d: "eau", t: "Big Ears Aren't Ugly: B-E-A-U. Then -tiful with one L." },
  { w: "favourite", l: 1, p: "our words", s: "Cheez Doodles are Nate's favourite food group.", h: "The one you like best.", d: "our", t: "favOURite has OUR in it. Cheez Doodles are OUR favourite. Don't drop the U." },
  { w: "finally", l: 1, p: "double letters", s: "Nate finally cleaned his locker. The sandwich at the bottom had grown a beard.", h: "After a long time.", d: "lly", t: "FINAL + LY. The two L's meet in the middle: final-ly." },
  { w: "friend", l: 1, p: "ie / ei", s: "Francis has been Nate's best friend since the sandpit incident. Neither of them will say what happened.", h: "Someone you like and trust.", d: "end", t: "A frIEnd sticks with you until the END. The END is right there: fri-END." },
  { w: "until", l: 1, p: "single letters", s: "Nate is grounded until he is approximately forty-five.", h: "Up to the time that.", d: "til", t: "Until has only one L. It's not fuLL yet. Detention isn't over unTIL it's over." },
  { w: "Wednesday", l: 1, p: "silent letters", s: "Nate has a reserved seat in Wednesday detention. It has his name scratched into it.", h: "The day after Tuesday.", d: "dnes", t: "Say it like a robot: WED. NES. DAY. The sneaky D and S hide in the middle, like Nate hiding homework." },
  { w: "February", l: 1, p: "silent letters", s: "February is the shortest month, but Nate's detention list still needed extra pages.", h: "The second month of the year.", d: "ru", t: "Feb-RU-ary. The RU is freezing and hiding: Feb-BRR-uary. Say the R out loud when you write it." },
  { w: "different", l: 1, p: "double letters", s: "Gina and Nate are so different they can't even agree on how to spell 'different'.", h: "Not the same.", d: "ffe", t: "Two F's, then ER: di-FFE-rent. And there's a RENT at the end: diffe-RENT." },
  { w: "thought", l: 1, p: "ought words", s: "Nate thought the test was next week. It was today.", h: "The past of think, an idea you had. Not the one meaning to have given a lesson.", d: "ought", t: "The OUGHT gang: thOUGHT, bOUGHT, brOUGHT. Learn OUGHT once and you own the whole gang." },
  { w: "caught", l: 1, p: "ought words", s: "Mrs. Godfrey caught Nate drawing her as a T. rex. The likeness did not help his case.", h: "Grabbed or discovered someone.", d: "augh", t: "You get cAUGHT, you get tAUGHT. Same -AUGHT ending. Mrs. Godfrey does both." },
  { w: "surprise", l: 1, p: "hidden letters", s: "The teacher announced a surprise quiz, so Nate announced a surprise headache.", h: "Something unexpected.", d: "rpr", t: "Don't lose the first R: suR-prise. A quiz can surprise you, but it can never 'suprise' you." },
  { w: "chocolate", l: 1, p: "hidden letters", s: "Nate traded his chocolate for a comic. Bold move.", h: "The best kind of sweet.", d: "co", t: "CHOC-O-LATE. The middle O is quiet but it's there. Never trade away the middle O." },
  { w: "colour", l: 1, p: "our words", s: "Nate's favourite colour is whatever Gina hates.", h: "Red, blue, green, and friends.", d: "our", t: "colOUR has OUR in it too. It's OUR colour, with a U. Same club as favOURite." },
  { w: "remember", l: 1, p: "letter patterns", s: "Nate can remember every Cheez Doodle flavour ever made, but not his own locker code.", h: "To keep something in your mind.", d: "mem", t: "re-MEM-ber: there's a MEMory in the middle. MEM. Even Nate can hold three letters." },
  { w: "minute", l: 1, p: "hidden letters", s: "Nate's record for emptying a bag of Cheez Doodles is one minute. He is furious it isn't faster.", h: "Sixty seconds.", d: "ute", t: "A tiny newt lives at the end: min-UTE. Sixty seconds, one newt." },
  { w: "island", l: 1, p: "silent letters", s: "Stranded on a desert island, Nate would build a raft, then use it as a table for Cheez Doodles.", h: "Land surrounded by water.", d: "isl", t: "An ISland IS LAND with water around it. The S is silent, like Nate when Mrs. Godfrey asks who did it." },
  { w: "answer", l: 1, p: "silent letters", s: "Nate guessed the answer. Confidently. Wrongly.", h: "The reply to a question.", d: "sw", t: "an-SW-er: the W is silent. It's there, just not talking. Very unlike Dee Dee." },
  { w: "people", l: 1, p: "letter patterns", s: "The cafeteria fits two hundred people and one food fight.", h: "More than one person.", d: "eo", t: "PEO: People Eat Oranges. Then -PLE. The O sneaks in before the P can stop it." },
  { w: "whole", l: 1, p: "silent letters", s: "Nate ate the whole bag. Obviously.", h: "The one that means all of it, complete. Not the one that means a gap or a pit.", d: "wh", t: "Silent W at the front, like WHO. WHO ate the WHOle bag? We all know who." },
  { w: "enough", l: 1, p: "ought words", s: "In the history of the world, nobody has ever said 'enough Cheez Doodles'. Nate checked.", h: "As much as is needed.", d: "ough", t: "e-NOUGH: the OUGH gang making an UFF sound this time." },
  { w: "guess", l: 1, p: "silent letters", s: "Guess who set off the fire alarm with an egg salad sandwich. Correct first time.", h: "An answer without knowing.", d: "gue", t: "GU-ESS: silent U after the G, then a double S." },
  { w: "heard", l: 1, p: "ear words", s: "Nate heard the ice cream van from three streets away. He cannot hear Mrs. Godfrey from one metre.", h: "The past of hear, done with your ears. Not a group of cows.", d: "ear", t: "You HEAR with your EAR: h-EAR-d. The ear stays in." },
  { w: "laugh", l: 1, p: "augh words", s: "Teddy tried not to laugh in assembly. He lasted four seconds. A school record.", h: "What you do at a good joke.", d: "augh", t: "L-AUGH: AUGH makes the AFF sound. Laughing is tough, like enough." },
  { w: "listen", l: 1, p: "silent letters", s: "Listen for Mrs. Godfrey's footsteps. Then run.", h: "To pay attention with your ears.", d: "ten", t: "Silent T: lis-T-en. The T listens quietly and says nothing." },
  { w: "often", l: 1, p: "silent letters", s: "Nate visits detention often. It's basically his office.", h: "Many times.", d: "ten", t: "Silent T, same as listen: of-T-en. The T clocks in but doesn't speak." },
  { w: "question", l: 1, p: "tion words", s: "Nate's answer had nothing to do with the question.", h: "Something you ask.", d: "tion", t: "QUEST + ION: every question is a QUEST. Nate treats them as optional quests." },
  { w: "trouble", l: 1, p: "ouble words", s: "Nate can find trouble in an empty room.", h: "Problems or difficulty.", d: "ouble", t: "TR + OUBLE. Double trouble: OUBLE is in both words." },
  { w: "young", l: 1, p: "ou words", s: "Nate plans to retire young. From homework.", h: "Not old.", d: "oun", t: "Y-OUNG: the OU makes an UH sound. Just memorise the OU. It's young and rebellious." },
  { w: "promise", l: 1, p: "ise words", s: "Nate made a promise to behave all day. It lasted eleven minutes, a personal best.", h: "Saying you will definitely do something.", d: "ise", t: "PROM + ISE: it ends in -ISE, not -iss. A promise you can spell is a promise you can break politely." },
  // Level 2
  { w: "recommend", l: 2, p: "double letters", s: "Teddy would not recommend the egg salad to his worst enemy. And Teddy keeps a list.", h: "To suggest something as good.", d: "comm", t: "RE + COMMEND. One C, two M's. Warn people about the egg salad twice as hard." },
  { w: "tomorrow", l: 2, p: "double letters", s: "The test is tomorrow. Nate's entire plan is for tomorrow to never arrive.", h: "The day after today.", d: "morr", t: "One M, two R's: to-MOR-ROW. Tomorrow is too far away to carry two M's." },
  { w: "receive", l: 2, p: "ie / ei", s: "Nate is about to receive his third detention slip this week. He is collecting the full set.", h: "To get something.", d: "cei", t: "I before E, except after C. That C flips it: re-CEI-ve. Gina never misses this one, so you can't either." },
  { w: "believe", l: 2, p: "ie / ei", s: "Nate cannot believe Artur won the raffle too. Nobody can. Artur wins everything.", h: "To accept something as true.", d: "lie", t: "Never beLIEve a LIE. The LIE is sitting right there in the middle." },
  { w: "weird", l: 2, p: "ie / ei", s: "Spitsy is a weird dog. He is scared of cats.", h: "Strange or unusual.", d: "ei", t: "Weird is weird. It breaks the I-before-E rule, the way Spitsy breaks all dog rules." },
  { w: "achieve", l: 2, p: "ie / ei", s: "Nate plans to achieve greatness, right after this nap.", h: "To succeed at something.", d: "chie", t: "I before E: a-CHIE-ve. It has CHIE in it, like CHIEF. Chief of doodles." },
  { w: "ceiling", l: 2, p: "ie / ei", s: "Nate's gum has been on the classroom ceiling so long it should pay rent.", h: "The top surface of a room.", d: "cei", t: "After C comes EI: CEI-ling. The gum stuck up there has had years to learn this." },
  { w: "vacuum", l: 2, p: "double vowels", s: "Nate's locker needs a vacuum, a shovel, and possibly a hazmat suit.", h: "A machine that sucks up dirt.", d: "uu", t: "One C, two U's. A vacUUm sucks Up, Up. Nate's locker would break it anyway." },
  { w: "calendar", l: 2, p: "unstressed vowels", s: "Nate's calendar has one entry: summer. Every other day is labelled 'obstacle'.", h: "A chart of days and months.", d: "dar", t: "It ends in -dAR. Read it like a pirate counting down to summer: calend-ARRR." },
  { w: "category", l: 2, p: "unstressed vowels", s: "In the category of doodling during class, Nate is world class.", h: "A group of similar things.", d: "cat", t: "It starts with CAT. Spitsy is terrified of the first three letters." },
  { w: "government", l: 2, p: "silent letters", s: "Class president today, running the whole government tomorrow. Nate has plans.", h: "The group that runs a country.", d: "rnm", t: "GOVERN + MENT. The N hides between R and M, like Nate hiding from Mrs. Godfrey." },
  { w: "immediately", l: 2, p: "double letters", s: "Mrs. Godfrey saw the drawing and gave out detention immediately. Light travels slower.", h: "Right away, without delay.", d: "mm", t: "Two M's: i-MM-ediately. Detention starts i-MM-ediately. There is no time to drop an M." },
  { w: "jealous", l: 2, p: "unstressed vowels", s: "Nate is not jealous of Artur. He just keeps a folder of everything Artur wins. For science.", h: "Wanting what someone else has.", d: "ea", t: "j-EA-lous. The EA is jealous nobody notices it. Then it ends in -OUS like famous." },
  { w: "knowledge", l: 2, p: "silent letters", s: "Francis shares his knowledge of jellyfish facts every single day. Nobody has ever asked.", h: "Facts and information you know.", d: "know", t: "KNOW + LEDGE. You KNOW a fact, then park it on a LEDGE. Francis has about nine thousand ledges." },
  { w: "lightning", l: 2, p: "silent letters", s: "When the lunch bell rings, Nate moves like lightning. In lessons, more like fog.", h: "Electric flash in the sky.", d: "htn", t: "Lightning is too fast for an extra E. LIGHT + NING. Add an E and you get 'lightening', which is what hair does." },
  { w: "neighbour", l: 2, p: "ie / ei", s: "Nate's neighbour pays him to walk Spitsy. In practice, Spitsy walks Nate.", h: "Someone who lives next door.", d: "eighbour", t: "EIGH like a horse saying neigh over the fence at Spitsy. And don't drop the U: good neighbOURs always bring U something." },
  { w: "pigeon", l: 2, p: "unstressed vowels", s: "A pigeon swiped Nate's last Cheez Doodle. Unforgivable.", h: "A common grey city bird.", d: "geo", t: "pi-GE-on. A sneaky E slips in before the ON, the same way that pigeon slipped in and took the Cheez Doodle." },
  { w: "scissors", l: 2, p: "double letters", s: "Dee Dee borrowed scissors for a quiet little art project. The glitter reached three classrooms.", h: "A tool for cutting paper.", d: "sciss", t: "SC at the start, double S in the middle: SCi-SS-ors. The SC is silent. Dee Dee is not." },
  { w: "stomach", l: 2, p: "silent letters", s: "Scientists should study Nate's stomach. It fears nothing, not even the canteen curry.", h: "The organ that digests food.", d: "ach", t: "It ends in -ACH but sounds like K. Easy to remember: stomACHe is what the cafeteria gives you." },
  { w: "actually", l: 2, p: "double letters", s: "Nate actually studied. The world did not end.", h: "In real fact.", d: "lly", t: "ACTUAL + LY. Two L's collide in the middle: actual-ly. Same crash as finally." },
  { w: "address", l: 2, p: "double letters", s: "Nate wrote the wrong address on the envelope. On purpose.", h: "Where someone lives.", d: "ddress", t: "ADD your aDDress: double D, double S. Generous word." },
  { w: "although", l: 2, p: "ought words", s: "Although the plan was clearly terrible, Teddy voted yes before Nate finished the sentence.", h: "Even though.", d: "ough", t: "AL with one L, then THOUGH. The OUGH gang strikes again." },
  { w: "decide", l: 2, p: "c and s sounds", s: "Nate couldn't decide between two pranks, so he did both. His detention was also doubled.", h: "To make a choice.", d: "cide", t: "de-CIDE: the C does the S sound, like in deCision. The referee has deCided." },
  { w: "disappear", l: 2, p: "double letters", s: "Nate's homework can disappear in broad daylight, in front of witnesses.", h: "To vanish from sight.", d: "sapp", t: "DIS + APPEAR: one S, two P's. The homework disappears. The P's never do." },
  { w: "disappoint", l: 2, p: "double letters", s: "The vending machine ran out of Cheez Doodles. No machine has ever managed to disappoint so many.", h: "To let someone down.", d: "sapp", t: "DIS + APPOINT: one S, two P's. Same family as disappear. They travel together." },
  { w: "doubt", l: 2, p: "silent letters", s: "There is no doubt who set up the bucket prank.", h: "Not being sure.", d: "bt", t: "Silent B: dou-B-t. The B hides, like Nate behind the bins." },
  { w: "forty", l: 2, p: "hidden letters", s: "Nate owes Francis forty cents. The interest is growing.", h: "The number 40.", d: "for", t: "FORTY loses the U that FOUR has. Four, fourteen... then forty goes rogue. No U." },
  { w: "guard", l: 2, p: "silent letters", s: "Nate stands guard over his snack drawer like it holds the crown jewels. It holds one biscuit.", h: "To protect something.", d: "gua", t: "GU-ARD: silent U after the G, like in GUess. The U is the quiet bodyguard." },
  { w: "humour", l: 2, p: "our words", s: "Mrs. Godfrey does not share Nate's sense of humour.", h: "Being funny.", d: "our", t: "humOUR: the OUR club again, with favOURite and colOUR. Membership requires a U." },
  { w: "important", l: 2, p: "ant words", s: "Nate missed the important part of the instructions. Also the start. And the end.", h: "Mattering a lot.", d: "ant", t: "import-ANT: there's an ANT at the end carrying something important. Ants always are." },
  { w: "library", l: 2, p: "hidden letters", s: "Nate got shushed in the library for laughing at his own comic.", h: "A building full of books.", d: "rar", t: "li-BRAR-y: two R's with only an A between them. Say lib-RA-ry slowly, like the librarian is watching." },
  { w: "opposite", l: 2, p: "double letters", s: "Gina and Nate sit on opposite sides of the classroom. Mrs. Godfrey measured it herself.", h: "Completely different.", d: "pp", t: "o-PP-osite: double P, single S. Opposites attract double P's." },
  { w: "potatoes", l: 2, p: "es plurals", s: "The canteen mashed potatoes could stop a door.", h: "More than one spud.", d: "oes", t: "One potato, two potat-OES: add ES, like heroes. The canteen potatoes are not heroes." },
  { w: "probably", l: 2, p: "hidden letters", s: "It was probably Nate. It was definitely Nate.", h: "Most likely.", d: "bab", t: "PROB-AB-LY: say all three chunks out loud. Don't squash the AB, even if Nate would." },
  { w: "science", l: 2, p: "ie / ei", s: "Nate's science project involved a volcano and regret.", h: "The study of how things work.", d: "cie", t: "SC first, then IE: sci-ence. Science breaks the I-before-E rule and writes its own." },
  { w: "special", l: 2, p: "cial words", s: "The lunch special is called 'Chef's Surprise'. The surprise is the chef won't eat it.", h: "Better or different from normal.", d: "cial", t: "spe-CIAL: the CIAL makes the SHUL sound. Special words get special endings." },
  { w: "straight", l: 2, p: "aigh words", s: "Nate can't draw a straight line without a ruler. Or with one.", h: "Not bent or curved.", d: "aigh", t: "str-AIGH-t: the AIGH gang, borrowed from eight. A straight line of silent letters." },
  { w: "suppose", l: 2, p: "double letters", s: "I suppose the fire drill wasn't Nate's fault. This time.", h: "To think something is likely.", d: "pp", t: "su-PP-ose: double P, like oPPosite. Suppose both P's showed up? They did." },
  { w: "through", l: 2, p: "ought words", s: "The paper plane sailed through the open door. Into Mrs. Godfrey.", h: "In one side and out the other, like going through a gate. Not the one meaning very careful, and not the past of throw.", d: "ough", t: "THR + OUGH: the OUGH gang making an OO sound this time. Same gang, new disguise." },
  { w: "usually", l: 2, p: "double letters", s: "Nate is usually late. Punctually late.", h: "Most of the time.", d: "ually", t: "USUAL + LY: usual-ly. Two L's meet, just like actually and finally. It's a club." },
  { w: "vegetable", l: 2, p: "hidden letters", s: "Nate treats every vegetable as a personal insult.", h: "Plant food like carrots and peas.", d: "eta", t: "veg-E-TABLE: there's a TABLE at the end. Put the vegetables on the TABLE, then don't eat them. Classic Nate." },
  { w: "cousin", l: 2, p: "hidden letters", s: "Nate's cousin found the emergency Cheez Doodles. Some things cannot be forgiven.", h: "Your aunt or uncle's child.", d: "ousi", t: "c-OUSI-n: the O-U-S-I squad in the middle. A cousin always brings extra vowels." },
  // Level 3
  { w: "separate", l: 3, p: "unstressed vowels", s: "Mrs. Godfrey moved Nate and Teddy to separate desks, then separate rooms. Separate schools are being discussed.", h: "To divide or keep apart.", d: "ara", t: "There's A RAT in sepARATe. Nate would name it Mr. Cheez." },
  { w: "definitely", l: 3, p: "unstressed vowels", s: "Someone drew on the whiteboard. It was definitely not Nate, says a note signed by Nate.", h: "Without any doubt.", d: "finite", t: "It's de-FINITE-ly. FINITE is hiding inside. There is no letter A in it, no matter what Nate scribbles." },
  { w: "embarrassed", l: 3, p: "double letters", s: "Nate was embarrassed when Ellen showed his baby bath photos to the whole class. With commentary.", h: "Feeling awkward or ashamed.", d: "rrass", t: "Double R, double S. Twice as embarrassing, like Ellen showing the baby photos. Both albums." },
  { w: "necessary", l: 3, p: "double letters", s: "Francis carries three spare pencils because it's necessary. Nate has never owned a pencil by Friday.", h: "Absolutely needed.", d: "cess", t: "One Collar, two Sleeves: one C, two S's. Even Nate's wrinkled shirt follows this rule." },
  { w: "occasionally", l: 3, p: "double letters", s: "Occasionally, Nate's locker avalanche misses him completely.", h: "Once in a while.", d: "ccas", t: "Two C's, one S. C's travel in pairs, like Nate and detention." },
  { w: "restaurant", l: 3, p: "silent letters", s: "Dad took them to a restaurant instead of cooking. The smoke alarm finally got a night off.", h: "A place where meals are served.", d: "au", t: "Rest-AU-rant. The sneaky AU in the middle is where Dad's wallet goes to rest." },
  { w: "rhythm", l: 3, p: "silent letters", s: "Nate's band has volume. Rhythm is still a work in progress.", h: "A repeated pattern of beats.", d: "hyth", t: "Rhythm Helps Your Two Hips Move. First letters spell it. No real vowels, just Y. Nate's band still can't find it." },
  { w: "licence", l: 3, p: "c and s sounds", s: "Ellen earned her driver's licence on the fourth attempt. Nate walks everywhere now.", h: "The official paper that lets you do something, spelled the noun way.", d: "cence", t: "The noun ends in -CE: li-CEN-CE, like advICE. You would give Ellen advice about her licence. License with an S is only the verb." },
  { w: "privilege", l: 3, p: "unstressed vowels", s: "Sitting far away from Gina is a privilege Nate has earned.", h: "A special right or advantage.", d: "lege", t: "It ends in -LEGE, like coLLEGE. No D anywhere. Detention has a D. Privilege doesn't." },
  { w: "environment", l: 3, p: "silent letters", s: "Detention is basically Nate's natural environment.", h: "The surroundings you live in.", d: "iron", t: "There's IRON in the middle: env-IRON-ment. The N before M is quiet but it's there." },
  { w: "independent", l: 3, p: "unstressed vowels", s: "Nate is an independent artist. His teachers call it doodling in class.", h: "Not needing help from others.", d: "dent", t: "It ends in -ENT, and every vowel after the first I is an E: independ-E-nt. E's all the way down." },
  { w: "mischievous", l: 3, p: "unstressed vowels", s: "When Nate gets his mischievous grin, Francis starts writing the apology letter early.", h: "Playfully causing trouble.", d: "chie", t: "MIS-CHIE-VOUS. Three syllables only. No extra I after the V, no matter how mischievous that grin is." },
  { w: "occurred", l: 3, p: "double letters", s: "The cafeteria food fight occurred right after the egg salad appeared.", h: "Happened.", d: "ccurr", t: "Doubles everywhere: two C's AND two R's. The food fight was big enough to double everything." },
  { w: "argument", l: 3, p: "hidden letters", s: "The argument was about the last Cheez Doodle. Obviously.", h: "A disagreement.", d: "gum", t: "There's GUM stuck in the middle of ar-GUM-ent. Argue drops its E before the fight starts." },
  { w: "awkward", l: 3, p: "letter pileups", s: "Nate waved back at someone who was waving at Gina, then finished the whole wave anyway. Awkward.", h: "Uncomfortable and clumsy.", d: "wkw", t: "Awkward is spelled awkwardly: W-K-W in a row. The word demonstrates itself." },
  { w: "business", l: 3, p: "hidden letters", s: "Nate's doodle business is booming. All profits are paid in Cheez Doodles.", h: "Buying, selling, or work.", d: "busi", t: "BUSY becomes BUSI-ness: the Y turns into an I when the NESS arrives. Business makes you busy." },
  { w: "character", l: 3, p: "ch as k", s: "Doctor Cesspool is Nate's greatest character.", h: "A person in a story.", d: "ch", t: "CH sounds like K: CHaracter. Same disguise as stomaCH. The CH is in character." },
  { w: "eighth", l: 3, p: "letter pileups", s: "Nate came eighth in the spelling bee. Ironic.", h: "Position number 8 in a line. Not how tall something is.", d: "ghth", t: "EIGHT + H: eigh-TH keeps all of eight, then adds an H. Four consonants queue at the end." },
  { w: "especially", l: 3, p: "cial words", s: "Nate hates tests, especially surprise ones.", h: "More than usual.", d: "ciall", t: "E + SPECIAL + LY: e-SPECIAL-ly. Special is hiding inside, wearing an E as a hat." },
  { w: "exercise", l: 3, p: "c and s sounds", s: "Coach John says exercise builds character. Nate remains unconvinced.", h: "Moving your body to stay fit.", d: "xerc", t: "e-XERC-ise: X first, then C. No S until the very end. The S skipped the workout." },
  { w: "experience", l: 3, p: "ence words", s: "Nate has so much detention experience he offers guided tours.", h: "Something that happens to you.", d: "ience", t: "exper-I-ENCE: ends in -ENCE. An experience you sit through, like science's boring cousin." },
  { w: "grammar", l: 3, p: "ar endings", s: "Gina corrects everyone's grammar. Everyone's.", h: "The rules of a language.", d: "mar", t: "grammAR ends in -AR. Bad gramm-ER is the trap. Gina would circle it in red." },
  { w: "height", l: 3, p: "ie / ei", s: "Nate's height ranking in class: not up for discussion.", h: "How tall something is. Not position number 8.", d: "eigh", t: "HEIGHT borrows EIGH from EIGHT, then ends in T. High and eight had a baby." },
  { w: "interrupt", l: 3, p: "double letters", s: "Never interrupt Nate mid-doodle. Dee Dee did it once. Once.", h: "To butt in while someone talks.", d: "rr", t: "inte-RR-upt: double R. You barge in with both R's or not at all." },
  { w: "peculiar", l: 3, p: "unstressed vowels", s: "A peculiar smell led everyone straight to Nate's locker.", h: "Odd or strange.", d: "liar", t: "A LIAR hides at the end of pecu-LIAR. Peculiar, but true." },
  { w: "possess", l: 3, p: "double letters", s: "Nate does not possess a single tidy habit.", h: "To own or have.", d: "ssess", t: "Four S's total: po-SS-e-SS. A greedy word. It possesses all the S's." },
  { w: "queue", l: 3, p: "silent letters", s: "Nate cut the lunch queue on pizza day. Survivors still talk about it.", h: "A line of people waiting.", d: "ueue", t: "Q does all the work while U-E-U-E queue up silently behind it. The most patient word in English." },
  { w: "strength", l: 3, p: "letter pileups", s: "It took the combined strength of Nate, Teddy and Francis to open Nate's locker. The locker fought back.", h: "Being strong.", d: "ngth", t: "STRONG becomes STRENGTH: an N-G-T-H pile-up at the end. Flex all four consonants." },
  { w: "tongue", l: 3, p: "silent letters", s: "Nate burnt his tongue on canteen soup that was somehow both frozen and volcanic.", h: "The thing you taste with.", d: "gue", t: "TON + GUE: ends in -GUE like league. The UE is silent, just showing off." },
  // Level 4
  { w: "accommodate", l: 4, p: "double letters", s: "The school hall can accommodate every kid and one very loud Dee Dee.", h: "To have room for.", d: "ccomm", t: "Two C's AND two M's. It's a big word with room for everyone: a-CC-o-MM-odate." },
  { w: "conscience", l: 4, p: "hidden letters", s: "Nate's conscience showed up three pranks too late.", h: "The little voice that knows right from wrong.", d: "science", t: "CON + SCIENCE. Your conscience is the SCIENCE of knowing better." },
  { w: "conscious", l: 4, p: "unstressed vowels", s: "Nate is technically conscious in first period. Technically.", h: "Awake and aware.", d: "sci", t: "CON-SCI-OUS: the SCI hides in the middle, like science with the end bitten off." },
  { w: "exaggerate", l: 4, p: "double letters", s: "Nate would never exaggerate. He's told us a billion times.", h: "To make something sound bigger than it is.", d: "gg", t: "One X, then a double G: exa-GG-erate. Exaggerating needs extra letters. Obviously." },
  { w: "guarantee", l: 4, p: "silent letters", s: "Chip can guarantee nothing except more spelling.", h: "A promise that something will happen.", d: "gua", t: "GUA at the start, like GUARD, then -RANTEE. A guarantee always guards its silent U." },
  { w: "noticeable", l: 4, p: "hidden letters", s: "The smell from Nate's locker is noticeable from the gym.", h: "Easy to see or notice.", d: "cea", t: "NOTICE keeps its E before -ABLE: notice-able. The E stays so the C stays soft." },
  { w: "occurrence", l: 4, p: "double letters", s: "A quiet day at P.S. 38 is a rare occurrence.", h: "Something that happens.", d: "ccurr", t: "Like occurred, but ending in -ENCE: two C's, two R's, then ENCE. Everything doubles except the ending." },
  { w: "parallel", l: 4, p: "double letters", s: "Nate and Gina live in parallel universes. Thankfully.", h: "Lines that never meet.", d: "llel", t: "The twin L's in the middle ARE parallel lines: para-LL-el. The word draws itself." },
  { w: "parliament", l: 4, p: "hidden letters", s: "Class president is one step from parliament, according to Nate.", h: "Where a country's laws get made.", d: "lia", t: "par-LIA-ment: I before A in the middle. Say par-LI-A-ment like a very posh robot." },
  { w: "persuade", l: 4, p: "unstressed vowels", s: "Teddy tried to persuade the canteen to serve pizza daily. His petition got four signatures. Two were his.", h: "To talk someone into something.", d: "suade", t: "PER + SUADE: the SUA squad in the middle. Per-SUA-de someone smoothly." },
  { w: "physically", l: 4, p: "silent letters", s: "Nate is physically incapable of tidying his locker.", h: "To do with the body.", d: "hys", t: "PH makes the F sound, then the Y sneaks in early: PH-Y-SIC-ALLY. Physical + LY, both L's included." },
  { w: "pronunciation", l: 4, p: "hidden letters", s: "Francis corrects Nate's pronunciation. Nate pronounces revenge.", h: "The way a word is said.", d: "nunci", t: "Pro-NUN-ciation, not pro-NOUN-ciation. The O from pronounce gets left in detention." },
  { w: "questionnaire", l: 4, p: "double letters", s: "Nate answered the careers questionnaire with 'cartoonist' fifteen times.", h: "A list of questions to answer.", d: "nn", t: "QUESTION + NAIRE with a double N handshake in the middle: question-naire." },
  { w: "recognise", l: 4, p: "hidden letters", s: "Teddy didn't recognise Nate in a tie. Nobody did.", h: "To know someone when you see them.", d: "gn", t: "RE-COG-NISE: there's a COG turning in the middle. Drop the G and the machine breaks." },
  { w: "sincerely", l: 4, p: "hidden letters", s: "Nate signed the apology letter 'sincerely unsorry'.", h: "Meaning it truly.", d: "cere", t: "SINCERE + LY: keep the whole word, just add LY. Sin-CERE-ly yours, Nate." },
  { w: "sufficient", l: 4, p: "double letters", s: "One warning is sufficient for most kids. Nate's teachers order warnings in bulk.", h: "Enough for the job.", d: "ffici", t: "Double F, then -ICIENT: su-FF-icient. The CI makes a SH sound, like special's sneaky cousin." },
  { w: "temperature", l: 4, p: "hidden letters", s: "The cafeteria soup has one temperature: volcano.", h: "How hot or cold something is.", d: "pera", t: "TEM-PER-A-TURE: say all four chunks out loud. The middle PERA is quiet but it's there." },
  { w: "thorough", l: 4, p: "ought words", s: "Mrs. Godfrey's homework checks are extremely thorough.", h: "The one that means very careful and complete, with nothing missed. Not the one about going in one side and out the other.", d: "orough", t: "THOROUGH is THROUGH with an extra O near the front: tho-ROUGH. The OUGH gang's longest member." },
  { w: "unnecessary", l: 4, p: "double letters", s: "Nate finds most rules deeply unnecessary.", h: "Not needed at all.", d: "nn", t: "UN + NECESSARY: the UN brings its own N, so it's u-NN-ecessary. One collar, two sleeves still applies." },
  { w: "manoeuvre", l: 4, p: "silent letters", s: "Dodging Mrs. Godfrey takes an expert manoeuvre.", h: "A skilful move.", d: "oeuv", t: "man-OEU-vre: the OEU is French and refuses to explain itself. Memorise the vowel pile: O, E, U." },
  { w: "millennium", l: 4, p: "double letters", s: "Cleaning Nate's locker is the project of the millennium.", h: "A thousand years.", d: "llenn", t: "Two L's AND two N's: mi-LL-e-NN-ium. A thousand years needs double everything." },
  { w: "apparently", l: 4, p: "double letters", s: "Apparently doodling counts as 'not listening'. Says Mrs. Godfrey.", h: "It seems that way.", d: "pp", t: "a-PP-arently: double P, and there's a PARENT hiding inside apparently. Don't tell Dad." },
  { w: "committee", l: 4, p: "double letters", s: "The prank planning committee meets behind the bins.", h: "A group that makes decisions.", d: "mmittee", t: "The greediest word in English: double M, double T, double E. Commi-TT-EE keeps them all." },
  { w: "desperate", l: 4, p: "unstressed vowels", s: "By Friday, Nate is desperate for the weekend.", h: "Wanting something very badly.", d: "sper", t: "des-PER-ate: PER, not PAR. A RAT lives in sepArate, but desperate stays PER-fect." },
  { w: "curiosity", l: 4, p: "hidden letters", s: "Curiosity got Nate into the teachers' lounge. Detention got him out.", h: "Wanting to know things.", d: "osi", t: "CURIOUS drops its U-S for -ITY: curi-OS-ity. The extra U from curious doesn't make the trip." },
  { w: "disastrous", l: 4, p: "hidden letters", s: "The volcano project was disastrous. Award-winningly disastrous.", h: "Terrible, like a disaster.", d: "strous", t: "DISASTER drops its E before -OUS: disastr-ous. The E saw the disaster coming and fled." },
];

export const HUNTER_PRAISE = [
  "Correct. Even Gina would be impressed. Don't tell her.",
  "Nailed it. Doodle yourself a trophy.",
  "Boom. Francis-level brain power.",
  "Right. You've earned one imaginary Cheez Doodle.",
  "Correct. Mrs. Godfrey has nothing on you.",
  "Flawless. P.S. 38 spelling legend status.",
  "Yep. Chip's wallet just flinched.",
  "Correct. Somewhere, Artur is nervous.",
  "That's the one. Teddy owes me a dollar, he bet against you.",
  "Right again. Dee Dee is composing a musical about it.",
  "Correct. Write that on the whiteboard and sign it 'definitely not Nate'.",
];

// Streak 3+: the trash talk heats up with the streak
export const HUNTER_PRAISE_HOT = [
  "You're ON FIRE. The sprinklers are worried.",
  "Another one?! Chip is checking the rulebook for a way out.",
  "Unstoppable. Mrs. Godfrey just filed a complaint.",
  "This is getting embarrassing. For Chip. Keep going.",
  "The streak lives! Gina has started a rumor that you're cheating.",
  "Chip is sweating actual pencil shavings.",
];

export const HUNTER_ROASTS = [
  "Nope. That earns you a Mrs. Godfrey glare.",
  "Wrong. Straight to spelling detention.",
  "Missed it. Even Spitsy could do better. Maybe.",
  "Oof. Gina just got another A plus somewhere.",
  "Incorrect. The word goes back in the pile for revenge.",
  "Nope. Locker avalanche of shame.",
  "Wrong, and Chip is doing his little victory doodle about it.",
  "Missed. The word is telling all its friends.",
  "Nope. That spelling goes on the fridge of shame.",
  "Incorrect. Somewhere a dictionary just sighed.",
];

export const HUNTER_GENERIC_TRICK = "No cheat sheet for this one. Stare at the letters. Take a brain photo. Nate calls that studying.";

export const HUNTER_BOSS_TAUNTS = [
  "I picked five words so nasty even Francis flinched. Free entry. Scared?",
  "Beat my gauntlet and I'll pay you out of my own Cheez Doodle fund. That's how confident I am.",
  "Five words. One miss allowed. My money says you choke on word three.",
  "The boss battle stands. Every day you don't accept, I doodle you losing.",
  "No bet, no excuses. Just you, me, and five words with detention energy.",
];

export const HUNTER_RANKS: Rank[] = [
  { wins: 0, title: "Rookie of Room 216" },
  { wins: 3, title: "Doodle Cadet" },
  { wins: 7, title: "Cheez Doodle Champ" },
  { wins: 12, title: "Prank Captain" },
  { wins: 18, title: "Locker Legend" },
  { wins: 25, title: "Detention Hall of Famer" },
  { wins: 35, title: "P.S. 38 Superstar" },
  { wins: 50, title: "Showdown Boss" },
  { wins: 75, title: "Big Time Big Shot" },
  { wins: 100, title: "Immortal Doodler" },
];

export const HUNTER_DOODLES: Doodle[] = [
  { id: "golden-doodle", icon: "🧀", name: "The Golden Cheez Doodle", cap: "One in a million. Do not eat.", rare: true },
  { id: "glue-incident", icon: "🧴", name: "The Glue Incident File", cap: "CLASSIFIED. Nobody talks about it.", rare: true },
  { id: "red-pen", icon: "🖊️", name: "Mrs. Godfrey's Red Pen", cap: "Runs dry twice a week. Entirely Nate's fault.", rare: false },
  { id: "detention-slip", icon: "📄", name: "Signed Detention Slip", cap: "Framed. Nate's most common trophy.", rare: false },
  { id: "lucky-pencil", icon: "✏️", name: "Nate's Lucky Pencil", cap: "Chewed on one end. Genius on the other.", rare: false },
  { id: "spitsy-cone", icon: "🐶", name: "Spitsy's Cone of Shame", cap: "He wears it with zero shame.", rare: false },
  { id: "fleece-ball", icon: "🧶", name: "Fleeceball Game Ball", cap: "MVP: not Gina. Never Gina.", rare: false },
  { id: "locker-medal", icon: "🏅", name: "Locker Avalanche Survivor Medal", cap: "Awarded for surviving Nate's locker. Twice.", rare: false },
  { id: "gina-aplus", icon: "💯", name: "One of Gina's A-Pluses", cap: "She has hundreds. She counted.", rare: false },
  { id: "joke-notebook", icon: "📓", name: "Teddy's Joke Notebook", cap: "Half the jokes are about egg salad.", rare: false },
  { id: "fact-book", icon: "📘", name: "Francis's Book of Facts", cap: "Volume 9 of 40. Jellyfish edition.", rare: false },
  { id: "hall-pass", icon: "🎫", name: "The Eternal Hall Pass", cap: "Expired in 2009. Still works.", rare: false },
];
